Repository openstack-k8s-operators/edpm-ansible, pull requests merged in 2023-05, with the labels that each got.

#135 Automate OVN chassis MAC addres prefixes
  roles/edpm_ovn/defaults/main.yml
Labels: approved, lgtm

#131 fixing no_networks scenario of edpm_ssh_known_hosts
  roles/edpm_ssh_known_hosts/molecule/no_networks/molecule.yml
  roles/edpm_ssh_known_hosts/molecule/no_networks/tests/test_no_networks.py
Labels: approved, lgtm

#132 Removing superfluous .gitkeep files
  roles/edpm_nova_compute/files/.gitkeep
  roles/edpm_nova_libvirt/files/.gitkeep
Labels: approved, lgtm

#134 Replace TripleO images by TCIB images
  molecule-requirements.txt
  roles/edpm_iscsid/defaults/main.yml
  roles/edpm_logrotate_crond/defaults/main.yml
  roles/edpm_nova_compute/defaults/main.yml
  roles/edpm_nova_libvirt/defaults/main.yml
  roles/edpm_nova_libvirt/molecule/run_virtqemud/test_vars.yml
  roles/edpm_ovn/defaults/main.yml
Labels: approved, lgtm

#140 Setting pin to version in order to fix issue caused by breaking chang…
  molecule-requirements.txt
Labels: approved, lgtm

#139 Setting molecule playbook to target localhost explictly
  .github/playbooks/molecule-run.yml
  .github/workflows/molecule.yaml
Labels: approved, lgtm

#143 Escalate privileges for edpdm_iscsid and edpm_tuned tasks
  roles/edpm_iscsid/tasks/configure.yml
  roles/edpm_tuned/tasks/configure.yml
Labels: approved, lgtm

#145 Replace TripleO frr image
  roles/edpm_frr/defaults/main.yml
  roles/edpm_ovn_bgp_agent/defaults/main.yml
Labels: approved, lgtm

#146 Use root privileges to write to /etc/iscsi
  roles/edpm_iscsid/tasks/configure.yml
Labels: approved, lgtm

#141 Adding edpm_ssh_known_hosts into CI test list
  .github/workflows/molecule.yaml
Labels: approved, lgtm

#147 Setting up molecule test for the edpm_nvdimm role
  .github/workflows/molecule.yaml
  roles/edpm_nvdimm/molecule/default/molecule.yml
Labels: approved, lgtm

#137 Turning README.rst into README.md
  README.md
Labels: approved, lgtm

#148 Setting up edpm_nova_compute molecule tests
  .github/workflows/molecule.yaml
  roles/edpm_nova_compute/molecule/default/molecule.yml
  roles/edpm_nova_compute/molecule/default/prepare.yml
Labels: bug, approved, lgtm

#155 Mocking imported module to avoid ansible-autodoc import error
  docs/source/conf.py
Labels: approved, lgtm

#158 chronyc makestep requires privilege escalation
  roles/edpm_chrony/tasks/sync.yml
  roles/edpm_timezone/tasks/run.yml
Labels: approved, lgtm

#154 Add Zuul based molecule jobs
  zuul.d/jobs.yaml
  zuul.d/playbooks/directories.yml
  zuul.d/playbooks/pre.yml
  zuul.d/playbooks/run-local.yml
  zuul.d/playbooks/run-role-addition.yml
  zuul.d/playbooks/run.yml
  zuul.d/projects.yaml
Labels: approved, lgtm

#159 Remove edpm_nvdimm role as no longer supported
  .github/workflows/molecule.yaml
  docs/source/roles/role-edpm_nvdimm.rst
  roles/edpm_nova_compute/defaults/main.yml
  roles/edpm_nova_compute/tasks/configure.yml
  roles/edpm_nvdimm/defaults/main.yml
  roles/edpm_nvdimm/files/.gitkeep
  roles/edpm_nvdimm/meta/main.yml
  roles/edpm_nvdimm/molecule/default/converge.yml
  roles/edpm_nvdimm/molecule/default/molecule.yml
  roles/edpm_nvdimm/molecule/default/prepare.yml
  roles/edpm_nvdimm/molecule/default/tests/test_default.py
  roles/edpm_nvdimm/tasks/create_namespaces.yml
  roles/edpm_nvdimm/tasks/main.yml
  roles/edpm_nvdimm/vars/.gitkeep
  scripts/test_roles.py
Labels: approved, lgtm

#166 Ensure bridge mappings do not have spaces
  roles/edpm_ovn/defaults/main.yml
Labels: approved, lgtm, ok-to-test

#170 Setting hugetlbfs gid to kolla preset in the bootstrap instead of the…
  roles/edpm_bootstrap/tasks/bootstrap.yml
  roles/edpm_kernel/tasks/kernelargs.yml
Labels: approved, lgtm

#161 Added EDPM based Zuul job
  ci/playbooks/build_runner_image.yaml
  zuul.d/jobs.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#150 Replacing check-byte-order-marker with fix-byte-order-marker hook
  .pre-commit-config.yaml
Labels: approved, lgtm

#163 Argspecs for edpm-ansible roles
  roles/edpm_bootstrap/meta/argument_specs.yml
  roles/edpm_ceph_client_files/meta/argument_specs.yml
  roles/edpm_chrony/meta/argument_specs.yml
  roles/edpm_container_manage/meta/argument_specs.yml
  roles/edpm_container_rm/meta/argument_specs.yml
  roles/edpm_container_standalone/meta/argument_specs.yml
  roles/edpm_frr/meta/argument_specs.yml
  roles/edpm_growvols/meta/argument_specs.yml
  roles/edpm_hosts_entries/meta/argument_specs.yml
  roles/edpm_iscsid/meta/argument_specs.yml
  roles/edpm_kernel/meta/argument_specs.yml
  roles/edpm_logrotate_crond/meta/argument_specs.yml
  roles/edpm_module_load/meta/argument_specs.yml
  roles/edpm_network_config/meta/argument_specs.yml
  roles/edpm_nftables/meta/argument_specs.yml
  roles/edpm_nodes_validation/meta/argument_specs.yml
  roles/edpm_nova_compute/meta/argument_specs.yml
  roles/edpm_nova_libvirt/meta/argument_specs.yml
  roles/edpm_nvdimm/meta/argument_specs.yml
  roles/edpm_ovn/meta/argument_specs.yml
  roles/edpm_ovn_bgp_agent/meta/argument_specs.yml
  roles/edpm_podman/meta/argument_specs.yml
  roles/edpm_ssh_known_hosts/meta/argument_specs.yml
  roles/edpm_sshd/meta/argument_specs.yml
  roles/edpm_timezone/meta/argument_specs.yml
  roles/edpm_tuned/meta/argument_specs.yml
  roles/env_data/meta/argument_specs.yml
  roles/test_deps/meta/argument_specs.yml
Labels: approved, lgtm

#162 Basic documentation for our filters
  plugins/filter/dict_to_list.yml
  plugins/filter/haskey.yml
  plugins/filter/needs_delete.yml
Labels: approved, lgtm

#167 Add NB DB certs config for ovn-bgp-agent NB driver
  roles/edpm_ovn_bgp_agent/templates/ovn-bgp-agent.conf.j2
Labels: approved, lgtm, needs-ok-to-test

#165 Remove linux bridge nic config examples
  roles/edpm_network_config/templates/net_config_linux_bridge.j2
  roles/edpm_network_config/templates/single_nic_linux_bridge_vlans/single_nic_linux_bridge_vlans.j2
  roles/edpm_network_config/templates/single_nic_linux_bridge_vlans/single_nic_linux_bridge_vlans_storage.j2
Labels: approved, lgtm

#173 `edpm_module_load` argspec definition and molecule tests
  roles/edpm_module_load/meta/argument_specs.yml
  roles/edpm_module_load/molecule/default/converge.yml
  roles/edpm_module_load/molecule/remove_module/converge.yml
  zuul.d/jobs.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm
