Repository openstack-k8s-operators/edpm-ansible, pull requests merged in 2023-06, with the labels that each got.

#174 Replacing IMG_BASE_TAG with IMAGE_TAG_BASE in README.md
  README.md
Labels: approved, lgtm

#168 Adding zuul job for `edpm_kernel` molecule tests
  zuul.d/jobs.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#175 Adding argument spec template to skeleton role
  contribute/_skeleton_role_/meta/argument_specs.yml.j2
Labels: approved, lgtm

#169 Added the telemetry role and playbooks to deploy telemetry agents
  .github/workflows/molecule.yaml
  playbooks/deploy_edpm_telemetry_ceilometer.yml
  playbooks/deploy_edpm_telemetry_infra.yml
  roles/edpm_telemetry/defaults/main.yml
  roles/edpm_telemetry/meta/argument_specs.yml
  roles/edpm_telemetry/meta/main.yml
  roles/edpm_telemetry/molecule/default/collections.yml
  roles/edpm_telemetry/molecule/default/converge.yml
  roles/edpm_telemetry/molecule/default/molecule.yml
  roles/edpm_telemetry/molecule/default/prepare.yml
  roles/edpm_telemetry/tasks/deploy_ceilometer.yml
  roles/edpm_telemetry/tasks/deploy_infra.yml
  roles/edpm_telemetry/tasks/main.yml
Labels: approved, lgtm

#152 Explaining lack of tests for edpm_nova_libvirt role
  .github/workflows/molecule.yaml
Labels: approved, lgtm

#176 antsibull-docs introduction
  .gitignore
  docs/build-docs.sh
  docs/doc8.ini
  docs/docs-requirements.txt
  docs/source/_exts/ansible-autodoc.py
  docs/source/antsibull-docs
  docs/source/conf.py
  docs/source/contributing_roles.rst
  docs/source/plugins.rst
  docs/source/plugins/action/action-container_systemd.rst
  docs/source/plugins/filter/filter-helpers.rst
  docs/source/plugins/modules/modules-container_config_data.rst
  docs/source/plugins/modules/modules-container_config_hash.rst
  docs/source/plugins/modules/modules-edpm-container-configs.rst
  docs/source/plugins/modules/modules-edpm-container-manage.rst
  docs/source/plugins/modules/modules-edpm_os_net_config.rst
  docs/source/plugins/modules/modules-edpm_os_net_config_mappings.rst
  docs/source/roles.rst
  docs/source/roles/role-edpm_bootstrap.rst
  docs/source/roles/role-edpm_ceph_client_files.rst
  docs/source/roles/role-edpm_chrony.rst
  docs/source/roles/role-edpm_container_manage.rst
  docs/source/roles/role-edpm_container_rm.rst
  docs/source/roles/role-edpm_container_standalone.rst
  docs/source/roles/role-edpm_growvols.rst
  docs/source/roles/role-edpm_hosts_entries.rst
  docs/source/roles/role-edpm_iscsid.rst
  docs/source/roles/role-edpm_kernel.rst
  docs/source/roles/role-edpm_logrotate_crond.rst
  docs/source/roles/role-edpm_module_load.rst
  docs/source/roles/role-edpm_network_config.rst
  docs/source/roles/role-edpm_nodes_validation.rst
  docs/source/roles/role-edpm_nova_compute.rst
  docs/source/roles/role-edpm_nova_libvirt.rst
  docs/source/roles/role-edpm_ovn.rst
  docs/source/roles/role-edpm_podman.rst
  docs/source/roles/role-edpm_ssh_known_hosts.rst
  docs/source/roles/role-edpm_sshd.rst
  docs/source/roles/role-edpm_timezone.rst
  docs/source/roles/role-edpm_tuned.rst
  docs/source/roles/role-env_data.rst
  docs/source/roles/role-test_deps.rst
  plugins/filter/dict_to_list.yml
  plugins/filter/haskey.yml
  plugins/filter/needs_delete.yml
  roles/edpm_container_manage/meta/argument_specs.yml
Labels: approved, lgtm

#178 Correct the enable-chassis-as-gw logic
  roles/edpm_ovn/defaults/main.yml
  roles/edpm_ovn/tasks/cleanup.yml
  roles/edpm_ovn/tasks/configure.yml
Labels: approved, lgtm, ok-to-test

#179 Creating molecule tests for the env_data support role
  .github/workflows/molecule.yaml
  roles/env_data/molecule/default/converge.yml
  roles/env_data/molecule/default/molecule.yml
  roles/env_data/molecule/default/prepare.yml
Labels: approved, lgtm

#181 Improving versatility of the env_data role
  roles/env_data/meta/argument_specs.yml
  roles/env_data/meta/main.yml
  roles/env_data/tasks/main.yml
Labels: approved, lgtm

#186 Changing URL of in order to retrieve the tripleo-repos pkg
  roles/test_deps/tasks/main.yml
Labels: approved, lgtm

#184 Add edpm_bootstrap_command
  roles/edpm_bootstrap/defaults/main.yml
  roles/edpm_bootstrap/molecule/default/converge.yml
  roles/edpm_bootstrap/molecule/default/molecule.yml
  roles/edpm_bootstrap/molecule/default/verify.yml
  roles/edpm_bootstrap/tasks/bootstrap.yml
Labels: approved, lgtm

#187 Add tripleo-repos package to Containerfile.j2 template
  molecule/common/Containerfile.j2
Labels: approved, lgtm, needs-ok-to-test

#188 Added task to restart NM after plugin installation and improved `systemrolename` gathering
  roles/edpm_network_config/tasks/main.yml
Labels: approved, lgtm

#190 Add epdm_baremetal job
  roles/edpm_network_config/tasks/network_config.yml
  zuul.d/jobs.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#192 Setting correct defaults for all compute nodes on telemetry playbooks…
  playbooks/deploy_edpm_telemetry_ceilometer.yml
  playbooks/deploy_edpm_telemetry_infra.yml
Labels: approved, lgtm

#193 Add a boolean variable to control if NetworkManager should control resolv.conf update
  roles/edpm_bootstrap/defaults/main.yml
  roles/edpm_bootstrap/tasks/bootstrap.yml
Labels: approved, lgtm

#194 Restart NetworkManager only when needed and renamed task
  roles/edpm_network_config/tasks/main.yml
Labels: approved, lgtm

#191 Set make_edpm_compute_baremetal var
  ci/playbooks/build_runner_image.yaml
Labels: approved, lgtm

#195 Added sentinel file to check if rules are changed so they can be applied
  roles/edpm_nftables/tasks/configure.yml
  roles/edpm_nftables/tasks/run.yml
Labels: approved, lgtm

#156 Manage swap partition as a hard requirement
  roles/edpm_bootstrap/defaults/main.yml
  roles/edpm_bootstrap/molecule/default/prepare.yml
  roles/edpm_bootstrap/tasks/bootstrap.yml
  roles/edpm_bootstrap/tasks/swap.yml
Labels: approved, lgtm

#196 Optimized the dependencies needed by molecule
  molecule-requirements.txt
Labels: approved, lgtm

#197 Fixing molecule tests of edpm_ceph_client_files so they can run locally
  .github/workflows/molecule.yaml
  roles/edpm_ceph_client_files/molecule/default/converge.yml
  roles/edpm_ceph_client_files/molecule/default/molecule.yml
Labels: approved, lgtm

#198 Multiple roles were added to the local test skip list
  scripts/test_roles.py
Labels: approved, lgtm

#203 Add edpm-ansible content provider job
  zuul.d/jobs.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#202 Removed playbooks since they aren't used anymore
  README.md
  docs/source/usage.rst
  playbooks/deploy_edpm_facts.yml
  playbooks/deploy_edpm_network_configure.yml
  playbooks/deploy_edpm_network_validate.yml
  playbooks/deploy_edpm_openstack_configure.yml
  playbooks/deploy_edpm_openstack_install.yml
  playbooks/deploy_edpm_openstack_run.yml
  playbooks/deploy_edpm_os_configure.yml
  playbooks/deploy_edpm_os_install.yml
  playbooks/deploy_edpm_os_run.yml
  playbooks/deploy_edpm_pre_network.yml
  playbooks/deploy_edpm_telemetry_ceilometer.yml
  playbooks/deploy_edpm_telemetry_infra.yml
  playbooks/prepare_test_host.yml
Labels: approved, lgtm

#205 Refactored swap Playbook in ansible style and changed swapfile default size
  roles/edpm_bootstrap/defaults/main.yml
  roles/edpm_bootstrap/tasks/swap.yml
Labels: approved, lgtm

#199 Set ansible runner image var for edpm_prepare role
  ci/playbooks/build_runner_image.yaml
Labels: approved, lgtm
