Repository openstack-k8s-operators/edpm-ansible, pull requests merged in 2023-09, with the labels that each got.

#301 edpm_kernel: Fix Reboot Task
  roles/edpm_kernel/tasks/reboot.yaml
Labels: approved, lgtm, ok-to-test

#307 Document building an ephemeral VM for local molecule testing
  docs/source/testing_roles.rst
Labels: approved, lgtm

#275 Refactoring telemetry playbooks to be compliant with spec.
  playbooks/deploy_edpm_telemetry_ceilometer.yaml
  playbooks/deploy_edpm_telemetry_infra.yaml
Labels: approved, lgtm

#286 DDP option role document changes
  docs/source/roles/role-edpm_ddp_package.rst
Labels: approved, lgtm

#312 adapt the telemetry playbooks to the new name and structure
  playbooks/deploy_edpm_telemetry_infra.yaml
  playbooks/telemetry.yaml
Labels: approved, lgtm

#313 Refactor Ceph libvirt secret management code
  roles/edpm_libvirt/defaults/main.yml
  roles/edpm_libvirt/molecule/default/prepare.yml
  roles/edpm_libvirt/molecule/default/test-helpers/verify_ceph_secret.yaml
  roles/edpm_libvirt/molecule/default/verify.yml
  roles/edpm_libvirt/tasks/post-install.yml
  roles/edpm_libvirt/tasks/virsh-secret.yml
  roles/edpm_libvirt/templates/libvirt_virtqemud/secret.xml.j2
Labels: approved, lgtm

#276 Revert "Removing MD5 from the list of approved algos"
  roles/edpm_iscsid/defaults/main.yml
  roles/edpm_iscsid/meta/argument_specs.yml
Labels: approved, lgtm

#317 Add ceph_rgw and ceph_rgw_frontend in te list of enabled_services
  roles/edpm_ceph_hci_pre/defaults/main.yml
Labels: approved, lgtm

#310 Remove unnecessary neutron config options from the edpm_ovn role
  roles/edpm_ovn/defaults/main.yml
  roles/edpm_ovn/meta/argument_specs.yml
  roles/edpm_ovn/tasks/configure.yml
  roles/edpm_ovn/templates/networking-ovn-metadata-agent.ini.j2
  roles/edpm_ovn/templates/neutron.conf.j2
  roles/edpm_ovn/templates/rootwrap.conf.j2
Labels: approved, lgtm

#282 relax nova config patteren
  roles/edpm_nova/molecule/default/test-data/nova-cell1/01-nova.conf
  roles/edpm_nova/molecule/default/test-data/nova-cell1/02-nova-log.conf
  roles/edpm_nova/molecule/default/verify.yml
  roles/edpm_nova/templates/config.json.j2
Labels: approved, lgtm

#311 Removing json_query calls
  plugins/filter/helpers.py
  plugins/filter/jump_chain_targets.yml
  roles/edpm_nftables/templates/jump-chain.j2
  roles/edpm_podman/templates/podman_network_config.j2
  roles/env_data/tasks/main.yml
Labels: approved, lgtm

#309 [ovn] Add missing firewall rules
  .github/workflows/molecule.yaml
  roles/edpm_ovn/molecule/default/verify.yml
  roles/edpm_ovn/tasks/firewall.yml
  roles/edpm_ovn/tasks/install.yml
  roles/edpm_ovn/tasks/main.yml
Labels: approved, lgtm

#326 Use RDO quay registry:2 image in podman molecule job
  roles/edpm_podman/molecule/login/prepare.yml
Labels: approved, lgtm

#320 Removing jmespath dependency for molecule tests
  molecule-requirements.txt
Labels: approved, lgtm

#324 ovn: fix metadata agent configuration
  roles/edpm_ovn/defaults/main.yml
  roles/edpm_ovn/meta/argument_specs.yml
  roles/edpm_ovn/tasks/configure.yml
  roles/edpm_ovn/tasks/install.yml
  roles/edpm_ovn/templates/kolla_ovn_metadata_agent.yaml.j2
  roles/edpm_ovn/templates/neutron-ovn-metadata-agent.conf.j2
Labels: approved, lgtm

#318 Run EDPM job from podified-multinode-edpm-pipeline job template
  zuul.d/jobs.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#332 Role edpm_ceph_hci_pre needs become to update firewall
  roles/edpm_ceph_hci_pre/tasks/firewall.yml
Labels: approved, lgtm

#330 Add `.vscode` to `.gitignore`
  .gitignore
Labels: approved, lgtm

#331 Enable download-cache support in `edpm_sshd` role
  roles/edpm_download_cache/tasks/main.yml
  roles/edpm_sshd/defaults/main.yml
  roles/edpm_sshd/meta/argument_specs.yml
  roles/edpm_sshd/molecule/default/verify.yml
  roles/edpm_sshd/tasks/configure.yml
  roles/edpm_sshd/tasks/download_cache.yml
  roles/edpm_sshd/tasks/install.yml
  roles/edpm_sshd/tasks/load_vars.yml
  roles/edpm_sshd/tasks/main.yml
  roles/edpm_sshd/vars/redhat.yml
Labels: approved, lgtm, download-cache

#339 Set network approvers for the repo
  OWNERS
  OWNERS_ALIASES
  roles/edpm_ovn/OWNERS
Labels: approved, lgtm

#325 Consume config files from secrets for metadata agent
  roles/edpm_ovn/defaults/main.yml
  roles/edpm_ovn/meta/argument_specs.yml
  roles/edpm_ovn/molecule/default/test-data/10-neutron-metadata.conf
  roles/edpm_ovn/molecule/default/verify.yml
  roles/edpm_ovn/tasks/configure.yml
Labels: approved, lgtm

#323 Enable download-cache for `edpm_tuned` role
  roles/edpm_download_cache/tasks/main.yml
  roles/edpm_tuned/defaults/main.yml
  roles/edpm_tuned/meta/argument_specs.yml
  roles/edpm_tuned/tasks/configure.yml
  roles/edpm_tuned/tasks/download_cache.yml
  roles/edpm_tuned/tasks/install.yml
  roles/edpm_tuned/tasks/main.yml
  roles/edpm_tuned/tasks/vars.yml
  roles/edpm_tuned/vars/redhat.yml
Labels: approved, lgtm, download-cache

#316 Add edpm role to deploy Neutron SRIOV agent
  .github/workflows/molecule.yaml
  playbooks/neutron_sriov.yaml
  roles/edpm_neutron_sriov/OWNERS
  roles/edpm_neutron_sriov/defaults/main.yml
  roles/edpm_neutron_sriov/files/.gitkeep
  roles/edpm_neutron_sriov/handlers/main.yml
  roles/edpm_neutron_sriov/meta/argument_specs.yml
  roles/edpm_neutron_sriov/meta/main.yml
  roles/edpm_neutron_sriov/molecule/default/collections.yml
  roles/edpm_neutron_sriov/molecule/default/converge.yml
  roles/edpm_neutron_sriov/molecule/default/molecule.yml
  roles/edpm_neutron_sriov/molecule/default/prepare.yml
  roles/edpm_neutron_sriov/molecule/default/verify.yml
  roles/edpm_neutron_sriov/tasks/configure.yml
  roles/edpm_neutron_sriov/tasks/install.yml
  roles/edpm_neutron_sriov/tasks/main.yml
  roles/edpm_neutron_sriov/tasks/run.yml
  roles/edpm_neutron_sriov/templates/kolla_config/neutron_sriov_agent.yaml.j2
  roles/edpm_neutron_sriov/templates/neutron-sriov-agent.ini.j2
  roles/edpm_neutron_sriov/templates/neutron.conf.j2
  roles/edpm_neutron_sriov/templates/neutron_sriov_agent.yaml.j2
  roles/edpm_neutron_sriov/templates/rootwrap.conf.j2
  roles/edpm_neutron_sriov/vars/main.yml
Labels: approved, lgtm

#335 Add firewall rules for ceph-nfs
  roles/edpm_ceph_hci_pre/defaults/main.yml
Labels: approved, lgtm

#337 Enable download-cache support in `edpm_chrony` role
  roles/edpm_chrony/defaults/main.yml
  roles/edpm_chrony/meta/argument_specs.yml
  roles/edpm_chrony/molecule/default/Dockerfile.j2
  roles/edpm_chrony/molecule/default/molecule.yml
  roles/edpm_chrony/molecule/default/prepare.yml
  roles/edpm_chrony/tasks/config.yml
  roles/edpm_chrony/tasks/download_cache.yml
  roles/edpm_chrony/tasks/install.yml
  roles/edpm_chrony/tasks/main.yml
  roles/edpm_chrony/tasks/run.yml
  roles/edpm_chrony/tasks/upgrade.yml
  roles/edpm_chrony/tasks/vars.yml
  roles/edpm_chrony/vars/RedHat.yml
  roles/edpm_chrony/vars/default.yml
  roles/edpm_download_cache/tasks/main.yml
Labels: approved, lgtm, download-cache

#329 Enable download-cache support in `edpm_podman` role
  roles/edpm_download_cache/tasks/main.yml
  roles/edpm_podman/defaults/main.yml
  roles/edpm_podman/handlers/main.yml
  roles/edpm_podman/meta/argument_specs.yml
  roles/edpm_podman/tasks/buildah_login.yml
  roles/edpm_podman/tasks/configure.yml
  roles/edpm_podman/tasks/download_cache.yml
  roles/edpm_podman/tasks/install.yml
  roles/edpm_podman/tasks/load_vars.yaml
  roles/edpm_podman/tasks/main.yml
  roles/edpm_podman/tasks/rsyslog.yml
  roles/edpm_podman/tasks/service.yml
Labels: approved, lgtm, download-cache

#338 Enable download-cache support in `edpm_logrotate_crond` role
  roles/edpm_download_cache/tasks/main.yml
  roles/edpm_logrotate_crond/defaults/main.yml
  roles/edpm_logrotate_crond/meta/argument_specs.yml
  roles/edpm_logrotate_crond/tasks/download_cache.yml
  roles/edpm_logrotate_crond/tasks/install.yml
Labels: approved, lgtm, download-cache

#319 add support for libvirt_guests to edpm_libvirt
  molecule/test-helpers/verify_systemd_service.yaml
  molecule/test-helpers/verify_systemd_unit.yaml
  roles/edpm_libvirt/handlers/main.yml
  roles/edpm_libvirt/molecule/default/verify.yml
  roles/edpm_libvirt/tasks/main.yml
  roles/edpm_libvirt/tasks/post-install.yml
  roles/edpm_libvirt/templates/edpm_libvirt.target
  roles/edpm_libvirt/templates/edpm_libvirt_guests.service
  roles/edpm_libvirt/templates/virt-guest-shutdown.target
  roles/edpm_neutron_sriov/molecule/default/verify.yml
  roles/edpm_nova/molecule/default/verify.yml
  roles/edpm_nova_compute/tasks/install.yml
Labels: approved, lgtm

#341 Repurpose network_config_override variable
  roles/edpm_network_config/defaults/main.yml
  roles/edpm_network_config/meta/argument_specs.yml
  roles/edpm_network_config/molecule/default/converge.yml
  roles/edpm_network_config/tasks/os_net_config.yml
Labels: approved, lgtm

#345 Enable `download-cache` support in `edpm_iscsid` role
  roles/edpm_download_cache/tasks/main.yml
  roles/edpm_iscsid/defaults/main.yml
  roles/edpm_iscsid/meta/argument_specs.yml
  roles/edpm_iscsid/tasks/download_cache.yml
Labels: approved, lgtm, download-cache

#352 Revert "Enable `download-cache` support in `edpm_iscsid` role"
  roles/edpm_download_cache/tasks/main.yml
  roles/edpm_iscsid/defaults/main.yml
  roles/edpm_iscsid/meta/argument_specs.yml
  roles/edpm_iscsid/tasks/download_cache.yml
Labels: approved, lgtm

#353 Refactored `edpm_download_cache` role
  roles/edpm_download_cache/defaults/main.yml
  roles/edpm_download_cache/meta/argument_specs.yml
  roles/edpm_download_cache/tasks/container_images.yml
  roles/edpm_download_cache/tasks/main.yml
  roles/edpm_download_cache/tasks/packages.yml
Labels: approved, lgtm

#355 Removed check-pr github workflow
  .github/workflows/check-pr.yaml
Labels: approved, lgtm

#334 extract host user,group and dir creation to edpm_users role
  playbooks/configure_network.yaml
  roles/edpm_bootstrap/tasks/bootstrap.yml
  roles/edpm_nova_libvirt/defaults/main.yml
  roles/edpm_nova_libvirt/meta/argument_specs.yml
  roles/edpm_nova_libvirt/tasks/install.yml
  roles/edpm_users/defaults/main.yml
  roles/edpm_users/files/.gitkeep
  roles/edpm_users/handlers/main.yml
  roles/edpm_users/meta/argument_specs.yml
  roles/edpm_users/meta/main.yml
  roles/edpm_users/molecule/default/converge.yml
  roles/edpm_users/molecule/default/molecule.yml
  roles/edpm_users/molecule/default/verify.yml
  roles/edpm_users/tasks/create_users_and_groups.yml
  roles/edpm_users/tasks/main.yml
  roles/edpm_users/vars/main.yml
Labels: approved, lgtm

#356 Enable `download-cache` support in `edpm_iscsid` role
  roles/edpm_download_cache/tasks/container_images.yml
  roles/edpm_iscsid/defaults/main.yml
  roles/edpm_iscsid/meta/argument_specs.yml
  roles/edpm_iscsid/tasks/download_cache.yml
Labels: approved, lgtm, download-cache

#350 Added some needed variables for dataplane integration
  roles/edpm_telemetry/defaults/main.yml
  roles/edpm_telemetry/meta/argument_specs.yml
  roles/edpm_telemetry/molecule/default/converge.yml
  roles/edpm_telemetry/molecule/default/prepare.yml
  roles/edpm_telemetry/tasks/deploy_ceilometer.yml
Labels: approved, lgtm

#354 Fix name of the config_src variable in neutron_sriov role
  roles/edpm_neutron_sriov/defaults/main.yml
  roles/edpm_neutron_sriov/meta/argument_specs.yml
  roles/edpm_neutron_sriov/molecule/default/converge.yml
  roles/edpm_neutron_sriov/tasks/configure.yml
Labels: approved, lgtm

#358 Enable `download-cache` support in `edpm_libvirt` role
  roles/edpm_download_cache/tasks/container_images.yml
  roles/edpm_libvirt/defaults/main.yml
  roles/edpm_libvirt/meta/argument_specs.yml
  roles/edpm_libvirt/tasks/download_cache.yml
Labels: approved, lgtm, download-cache

#351 Replace `package` module with `dnf` in `edpm_sshd` role
  roles/edpm_sshd/tasks/install.yml
Labels: approved, lgtm

#362 Rework network_config_template to accept j2
  roles/edpm_network_config/defaults/main.yml
  roles/edpm_network_config/meta/argument_specs.yml
  roles/edpm_network_config/molecule/default/converge.yml
  roles/edpm_network_config/tasks/os_net_config.yml
Labels: approved, lgtm

#340 Add edpm_multipathd role
  playbooks/configure_os.yaml
  playbooks/install_os.yaml
  playbooks/run_os.yaml
  roles/edpm_multipathd/defaults/main.yml
  roles/edpm_multipathd/files/custom_multipath.conf
  roles/edpm_multipathd/files/multipath.conf
  roles/edpm_multipathd/meta/argument_specs.yml
  roles/edpm_multipathd/meta/main.yml
  roles/edpm_multipathd/molecule/custom_config/converge.yml
  roles/edpm_multipathd/molecule/custom_config/molecule.yml
  roles/edpm_multipathd/molecule/custom_config/prepare.yml
  roles/edpm_multipathd/molecule/custom_config/verify.yml
  roles/edpm_multipathd/molecule/default/converge.yml
  roles/edpm_multipathd/molecule/default/molecule.yml
  roles/edpm_multipathd/molecule/default/prepare.yml
  roles/edpm_multipathd/molecule/default/verify.yml
  roles/edpm_multipathd/molecule/preexisting_config/converge.yml
  roles/edpm_multipathd/molecule/preexisting_config/molecule.yml
  roles/edpm_multipathd/molecule/preexisting_config/prepare.yml
  roles/edpm_multipathd/molecule/preexisting_config/verify.yml
  roles/edpm_multipathd/tasks/configure.yml
  roles/edpm_multipathd/tasks/install.yml
  roles/edpm_multipathd/tasks/main.yml
  roles/edpm_multipathd/tasks/run.yml
  roles/edpm_multipathd/templates/kolla_multipathd.yaml.j2
  roles/edpm_multipathd/templates/multipathd.yaml.j2
  roles/edpm_nova/molecule/default/prepare.yml
  roles/edpm_nova/tasks/configure.yml
  roles/edpm_nova/templates/nova_compute.json.j2
Labels: approved, lgtm

#366 Support download-cache in edpm_multipathd role
  roles/edpm_download_cache/tasks/container_images.yml
  roles/edpm_multipathd/defaults/main.yml
  roles/edpm_multipathd/meta/argument_specs.yml
  roles/edpm_multipathd/tasks/download_cache.yml
Labels: approved, lgtm

#359 Enable `download-cache` support in `edpm_nova` role
  roles/edpm_download_cache/tasks/container_images.yml
  roles/edpm_nova/defaults/main.yml
  roles/edpm_nova/meta/argument_specs.yml
  roles/edpm_nova/tasks/download_cache.yml
Labels: approved, lgtm, download-cache

#365 edpm_libvirt role should handle quoted cephx keys
  roles/edpm_libvirt/tasks/virsh-secret.yml
Labels: approved, lgtm

#364 Do not attempt to manage collocated Ceph containers
  docs/source/roles/role-edpm_container_manage.rst
  roles/edpm_container_manage/tasks/delete_orphan.yml
Labels: approved, lgtm

#357 Enable `download-cache` support in `edpm_ovn` role
  roles/edpm_download_cache/tasks/container_images.yml
  roles/edpm_ovn/defaults/main.yml
  roles/edpm_ovn/meta/argument_specs.yml
  roles/edpm_ovn/tasks/download_cache.yml
Labels: approved, lgtm, download-cache

#370 Create systemd files requires root
  roles/edpm_telemetry/tasks/deploy_infra.yml
Labels: approved, lgtm

#160 Extract KSM management task
  playbooks/configure_network.yaml
  roles/edpm_bootstrap/defaults/main.yml
  roles/edpm_bootstrap/meta/argument_specs.yml
  roles/edpm_kernel/defaults/main.yml
  roles/edpm_kernel/handlers/main.yml
  roles/edpm_kernel/meta/argument_specs.yml
  roles/edpm_kernel/tasks/ksm.yml
  roles/edpm_nova_compute/defaults/main.yml
  roles/edpm_nova_compute/meta/argument_specs.yml
  roles/edpm_nova_compute/tasks/configure.yml
Labels: approved, lgtm

#371 Enable download-cache support in edpm_neutron_sriov role
  roles/edpm_download_cache/tasks/container_images.yml
  roles/edpm_neutron_sriov/defaults/main.yml
  roles/edpm_neutron_sriov/meta/argument_specs.yml
  roles/edpm_neutron_sriov/tasks/download_cache.yml
Labels: approved, lgtm

#372 podman_containers plugin is not working consistently, so replaced by …
  roles/edpm_telemetry/tasks/deploy_infra.yml
Labels: approved, lgtm

#374 Replace CI approvers
  OWNERS_ALIASES
Labels: approved, lgtm

#376 Set correct default for SRIOV agent report_interval
  roles/edpm_neutron_sriov/defaults/main.yml
  roles/edpm_neutron_sriov/meta/argument_specs.yml
Labels: approved, lgtm

#367 Remove network_config_override variable
  roles/edpm_network_config/defaults/main.yml
  roles/edpm_network_config/meta/argument_specs.yml
  roles/edpm_network_config/molecule/default/converge.yml
  roles/edpm_network_config/tasks/os_net_config.yml
Labels: approved, lgtm

#378 The podman create container must be done under root, so added become
  roles/edpm_telemetry/tasks/deploy_infra.yml
Labels: approved, lgtm

#380 Fix linting issues in edpm_telemetry role
  roles/edpm_telemetry/defaults/main.yml
  roles/edpm_telemetry/molecule/default/converge.yml
  roles/edpm_telemetry/molecule/default/prepare.yml
  roles/edpm_telemetry/tasks/deploy_ceilometer.yml
  roles/edpm_telemetry/tasks/deploy_infra.yml
Labels: approved, lgtm

#361 edpm_container_manage treat override as regex
  plugins/modules/edpm_container_manage.py
Labels: approved, lgtm, ok-to-test

#381 Upgrade collection requirements during ansibleee runner build
  openstack_ansibleee/Dockerfile
Labels: approved, lgtm

#336 Select DDP package only when required
  playbooks/select_kernel_ddp_package.yml
  roles/edpm_ddp_package/tasks/main.yml
Labels: approved, lgtm

#360 SR-IOV is not configured when the provider is not set
  plugins/modules/edpm_os_net_config.py
Labels: approved, lgtm
