Repository openstack-k8s-operators/edpm-ansible, pull requests merged in 2023-08, with the labels that each got.

#236 Argspec for edpm_ovn role
  docs/source/roles/role-edpm_ovn.rst
  roles/edpm_ovn/meta/argument_specs.yml
Labels: approved, lgtm, argspecs

#252 Updating OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, lgtm

#253 Replace package module with dnf module
  roles/edpm_bootstrap/tasks/bootstrap.yml
  roles/edpm_bootstrap/tasks/packages.yml
Labels: approved, lgtm

#267 Update docs on testing roles with molecule
  docs/source/contributing_roles.rst
Labels: approved, lgtm

#266 Adding validate_network playbook
  playbooks/validate_network.yaml
Labels: approved, lgtm, playbook-migration

#217 edpm nova
  docs/build-docs.sh
  docs/docs-requirements.txt
  molecule/test-helpers/verify_dir.yaml
  molecule/test-helpers/verify_podman.yaml
  molecule/test-helpers/verify_systemd_service.yaml
  roles/edpm_libvirt/defaults/main.yml
  roles/edpm_libvirt/files/.gitkeep
  roles/edpm_libvirt/handlers/main.yml
  roles/edpm_libvirt/meta/argument_specs.yml
  roles/edpm_libvirt/meta/main.yml
  roles/edpm_libvirt/molecule/default/README.md
  roles/edpm_libvirt/molecule/default/converge.yml
  roles/edpm_libvirt/molecule/default/molecule.yml
  roles/edpm_libvirt/molecule/default/prepare.yml
  roles/edpm_libvirt/molecule/default/test-helpers/verify_firewall.yaml
  roles/edpm_libvirt/molecule/default/verify.yml
  roles/edpm_libvirt/tasks/configure.yml
  roles/edpm_libvirt/tasks/install.yml
  roles/edpm_libvirt/tasks/main.yml
  roles/edpm_libvirt/tasks/post-install.yml
  roles/edpm_libvirt/templates/firewall.yaml
  roles/edpm_libvirt/templates/libvirt_virtlogd/config.json.j2
  roles/edpm_libvirt/templates/libvirt_virtlogd/libvirt_virtlogd.json.j2
  roles/edpm_libvirt/templates/libvirt_virtlogd/virtlogd.conf
  roles/edpm_libvirt/templates/libvirt_virtnodedevd/config.json.j2
  roles/edpm_libvirt/templates/libvirt_virtnodedevd/libvirt_virtnodedevd.json.j2
  roles/edpm_libvirt/templates/libvirt_virtnodedevd/virtnodedevd.conf
  roles/edpm_libvirt/templates/libvirt_virtproxyd/config.json.j2
  roles/edpm_libvirt/templates/libvirt_virtproxyd/libvirt_virtproxyd.json.j2
  roles/edpm_libvirt/templates/libvirt_virtproxyd/virtproxyd.conf
  roles/edpm_libvirt/templates/libvirt_virtqemud/config.json.j2
  roles/edpm_libvirt/templates/libvirt_virtqemud/libvirt_virtqemud.json.j2
  roles/edpm_libvirt/templates/libvirt_virtqemud/qemu.conf
  roles/edpm_libvirt/templates/libvirt_virtqemud/virtqemud.conf
  roles/edpm_libvirt/templates/libvirt_virtsecretd/config.json.j2
  roles/edpm_libvirt/templates/libvirt_virtsecretd/libvirt_virtsecretd.json.j2
  roles/edpm_libvirt/templates/libvirt_virtsecretd/virtsecretd.conf
  roles/edpm_libvirt/vars/main.yml
  roles/edpm_nova/defaults/main.yml
  roles/edpm_nova/files/.gitkeep
  roles/edpm_nova/handlers/main.yml
  roles/edpm_nova/meta/argument_specs.yml
  roles/edpm_nova/meta/main.yml
  roles/edpm_nova/molecule/default/converge.yml
  roles/edpm_nova/molecule/default/molecule.yml
  roles/edpm_nova/molecule/default/prepare.yml
  roles/edpm_nova/molecule/default/test-data/nova-cell1/01-nova.conf
  roles/edpm_nova/molecule/default/verify.yml
  roles/edpm_nova/tasks/configure.yml
  roles/edpm_nova/tasks/install.yml
  roles/edpm_nova/tasks/main.yml
  roles/edpm_nova/tasks/post-install.yml
  roles/edpm_nova/templates/config.json.j2
  roles/edpm_nova/templates/nova-blank.conf
  roles/edpm_nova/templates/nova_compute.json.j2
  roles/edpm_nova/vars/main.yml
  scripts/test_roles.py
  zuul.d/jobs.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#269 update usage of test_deps in nova and libvirt roles
  roles/edpm_libvirt/molecule/default/prepare.yml
  roles/edpm_nova/molecule/default/prepare.yml
Labels: approved, lgtm

#239 Argspecs for edpm_frr role
  roles/edpm_frr/meta/argument_specs.yml
Labels: approved, lgtm, argspecs

#255 remove O(n*m) loop from edpm_kernel
  roles/edpm_kernel/tasks/main.yml
Labels: approved, lgtm

#256 Adding configure_frr playbook
  playbooks/configure_frr.yaml
Labels: approved, lgtm, playbook-migration

#271 Use ansible_nodename for ovn chassis hostname
  roles/edpm_ovn/defaults/main.yml
  roles/edpm_ovn/meta/argument_specs.yml
Labels: approved, lgtm

#247 Argspecs for edpm_nova_libvirt role
  roles/edpm_nova_libvirt/meta/argument_specs.yml
Labels: approved, lgtm, argspecs

#257 Adding configure_network playbook
  playbooks/configure_network.yaml
Labels: approved, lgtm, playbook-migration

#258 Adding configure_os playbook
  playbooks/configure_os.yaml
Labels: approved, lgtm, playbook-migration

#265 Adding run_ovn_bgp_agent playbook
  playbooks/run_ovn_bgp_agent.yaml
Labels: approved, lgtm, playbook-migration

#248 Removing edpm_hosts_entries role
  .github/workflows/molecule.yaml
  docs/source/roles/role-edpm_hosts_entries.rst
  roles/edpm_hosts_entries/defaults/main.yml
  roles/edpm_hosts_entries/files/.gitkeep
  roles/edpm_hosts_entries/handlers/main.yml
  roles/edpm_hosts_entries/meta/argument_specs.yml
  roles/edpm_hosts_entries/meta/main.yml
  roles/edpm_hosts_entries/molecule/default/collections.yml
  roles/edpm_hosts_entries/molecule/default/converge.yml
  roles/edpm_hosts_entries/molecule/default/molecule.yml
  roles/edpm_hosts_entries/molecule/default/prepare.yml
  roles/edpm_hosts_entries/molecule/default/verify.yml
  roles/edpm_hosts_entries/tasks/main.yml
  roles/edpm_hosts_entries/vars/main.yml
Labels: approved, lgtm

#264 Adding run_os playbook
  playbooks/run_os.yaml
Labels: approved, lgtm, playbook-migration

#261 Adding install_os playbook
  playbooks/install_os.yaml
Labels: approved, lgtm, playbook-migration

#273 Introduce edpm_ceph_hci_pre role
  docs/source/roles/role-edpm_ceph_hci_pre.rst
  playbooks/ceph_hci_pre.yaml
  roles/edpm_ceph_hci_pre/defaults/main.yml
  roles/edpm_ceph_hci_pre/files/.gitkeep
  roles/edpm_ceph_hci_pre/handlers/main.yml
  roles/edpm_ceph_hci_pre/meta/argument_specs.yml
  roles/edpm_ceph_hci_pre/meta/main.yml
  roles/edpm_ceph_hci_pre/molecule/default/converge.yml
  roles/edpm_ceph_hci_pre/molecule/default/molecule.yml
  roles/edpm_ceph_hci_pre/molecule/default/prepare.yml
  roles/edpm_ceph_hci_pre/molecule/default/verify.yml
  roles/edpm_ceph_hci_pre/tasks/firewall.yml
  roles/edpm_ceph_hci_pre/tasks/main.yml
  roles/edpm_ceph_hci_pre/templates/firewall.yaml.j2
  roles/edpm_ceph_hci_pre/vars/main.yml
Labels: approved, lgtm

#260 Adding install_frr playbook
  playbooks/install_frr.yaml
Labels: approved, lgtm, playbook-migration

#259 Adding configure_ovn_bgp_agent playbook
  playbooks/configure_ovn_bgp_agent.yaml
Labels: approved, lgtm, playbook-migration

#262 Adding install_ovn_bgp_agent playbook
  playbooks/install_ovn_bgp_agent.yaml
Labels: approved, lgtm, playbook-migration

#277 Pinning molecule to avoid testinfra removal
  molecule-requirements.txt
Labels: approved, lgtm

#278 Skip edpm jobs when molecule-requirements.txt is modified
  zuul.d/jobs.yaml
Labels: approved, lgtm

#279 Adding ceph_client playbook from dataplane services
  playbooks/ceph_client.yaml
Labels: approved, lgtm, playbook-migration

#280 Adding ovn, nova and libvirt playbooks ported from dataplane services
  playbooks/libvirt.yaml
  playbooks/nova.yaml
  playbooks/ovn.yaml
Labels: approved, lgtm, playbook-migration

#274 Add tc command
  roles/edpm_bootstrap/defaults/main.yml
  roles/edpm_bootstrap/meta/argument_specs.yml
Labels: approved, lgtm

#216 Rolespec for edpm-ansible
  docs/source/contributing.rst
  docs/source/contributing_plugins.rst
  docs/source/contributing_roles.rst
  docs/source/index.rst
  docs/source/testing_roles.rst
  docs/source/testing_with_ansibleee.rst
  docs/source/usage.rst
Labels: approved, lgtm

#289 Installing collections before testing
  .github/workflows/molecule.yaml
  scripts/molecule_venv.sh
Labels: approved, lgtm

#290 Do not require a source address for ceph_hci_pre firewall
  roles/edpm_ceph_hci_pre/defaults/main.yml
  roles/edpm_ceph_hci_pre/meta/argument_specs.yml
  roles/edpm_ceph_hci_pre/molecule/default/converge.yml
  roles/edpm_ceph_hci_pre/molecule/default/prepare.yml
  roles/edpm_ceph_hci_pre/molecule/default/verify.yml
  roles/edpm_ceph_hci_pre/tasks/firewall.yml
  roles/edpm_ceph_hci_pre/templates/firewall.yaml.j2
Labels: approved, lgtm

#201 Full documentation for edpm_network_config role endpoint
  plugins/modules/edpm_os_net_config.py
  roles/edpm_network_config/defaults/main.yml
  roles/edpm_network_config/meta/argument_specs.yml
Labels: approved, lgtm, argspecs

#287 Add a comment explaining the intent of the SKIP_LIST
  scripts/test_roles.py
Labels: approved, lgtm

#293 Test edpm_ovn when running execute_molecule_local
  scripts/test_roles.py
Labels: approved, lgtm

#295 Update example kolla config file of ceilometer services in molecule
  roles/edpm_telemetry/molecule/default/prepare.yml
Labels: approved, lgtm

#296 Fix run_ovn_bgp_agent playbook definition
  playbooks/run_ovn_bgp_agent.yaml
Labels: approved, lgtm

#291 Replace Ubuntu with Fedora
  roles/edpm_podman/molecule/login/prepare.yml
Labels: approved, lgtm

#297 Remove ovn role include from os setup
  playbooks/configure_os.yaml
  playbooks/install_os.yaml
  playbooks/run_os.yaml
Labels: approved, lgtm

#302 Store Ceph client files in /var/lib/openstack/config/ceph
  roles/edpm_ceph_client_files/defaults/main.yml
  roles/edpm_ceph_client_files/meta/argument_specs.yml
  roles/edpm_libvirt/tasks/post-install.yml
Labels: approved, lgtm

#292 edpm_libivirt should reload NFT ruleset after configuring it
  roles/edpm_libvirt/molecule/default/prepare.yml
  roles/edpm_libvirt/tasks/post-install.yml
  roles/edpm_nova/molecule/default/prepare.yml
Labels: approved, lgtm

#304 Don't override the compute routing
  roles/edpm_network_config/templates/ci/extracted_crc_nic2_vlans.j2
Labels: approved, lgtm

#283 Switch to sha256 for config hash
  Makefile
  plugins/modules/container_config_hash.py
Labels: approved, lgtm

#308 Remove ci-framework network template
  roles/edpm_network_config/templates/ci/extracted_crc_nic2_vlans.j2
Labels: approved, lgtm

#285 Use new content provider and standalone crc based edpm job
  zuul.d/jobs.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm
