Repository openstack-k8s-operators/edpm-ansible, pull requests merged in 2023-03, with the labels that each got.

#63 Fix epdm -> edpm typos
  edpm_ansible/roles/edpm_chrony/README.rst
  edpm_ansible/roles/edpm_chrony/defaults/main.yml
  edpm_ansible/roles/edpm_chrony/handlers/main.yml
  edpm_ansible/roles/edpm_chrony/tasks/config.yml
  edpm_ansible/roles/edpm_chrony/tasks/install.yml
  edpm_ansible/roles/edpm_chrony/tasks/main.yml
  edpm_ansible/roles/edpm_chrony/tasks/run.yml
  edpm_ansible/roles/edpm_chrony/tasks/upgrade.yml
  edpm_ansible/roles/edpm_chrony/templates/chrony.conf.j2
  edpm_ansible/roles/edpm_chrony/tests/all.yml
  edpm_ansible/roles/edpm_chrony/tests/config.yml
  edpm_ansible/roles/edpm_chrony/tests/install.yml
  edpm_ansible/roles/edpm_chrony/tests/upgrade.yml
  edpm_ansible/roles/edpm_chrony/vars/RedHat.yml
Labels: approved, lgtm

#64 Added LICENSE file
  LICENSE
Labels: approved, lgtm

#66 Fixing license file linter error
  LICENSE
Labels: approved, lgtm, needs-ok-to-test

#67 Do not dump container definitions
  edpm_ansible/roles/edpm_container_standalone/tasks/main.yml
Labels: approved, lgtm

#65 Refactoring helpers module to be somewhat more pythonic
  edpm_ansible/ansible_plugins/filter/helpers.py
Labels: approved, lgtm, needs-ok-to-test

#69 use stable/zed images by default
  edpm_ansible/roles/edpm_iscsid/defaults/main.yml
  edpm_ansible/roles/edpm_logrotate_crond/defaults/main.yml
  edpm_ansible/roles/edpm_nova_compute/defaults/main.yml
  edpm_ansible/roles/edpm_nova_libvirt/defaults/main.yml
  edpm_ansible/roles/edpm_nova_libvirt/molecule/run_virtqemud/test_vars.yml
  edpm_ansible/roles/edpm_ovn/defaults/main.yml
Labels: approved, lgtm

#70 Removed containers-common downgrade workaround
  zuul.d/playbooks/directories.yml
  zuul.d/playbooks/pre.yml
Labels: approved, lgtm

#73 Changing default ci-framework repo path to fix conditional
  Makefile
Labels: approved, lgtm, needs-ok-to-test

#77 Correct how molecule is launched from within a container
  Makefile
Labels: approved, lgtm

#78 Correct how molecule is launched
  Makefile
Labels: approved, lgtm

#79 updated pre-commit tests
  .pre-commit-config.yaml
Labels: approved, lgtm

#81 Removing existing 'execute_molecule_tests' target
  Makefile
  README.rst
Labels: approved, lgtm

#80 Remove plan and edpm_stack_name
  roles/edpm_hosts_entries/molecule/default/molecule.yml
  roles/edpm_hosts_entries/tasks/main.yml
Labels: approved, lgtm

#83 Setting default verbosity of molecule tests
  Makefile
Labels: enhancement, approved, lgtm

#74 Add a growvols role and playbook
  edpm_ansible/roles/edpm_growvols/defaults/main.yml
  edpm_ansible/roles/edpm_growvols/meta/main.yml
  edpm_ansible/roles/edpm_growvols/molecule/default/converge.yml
  edpm_ansible/roles/edpm_growvols/molecule/default/molecule.yml
  edpm_ansible/roles/edpm_growvols/molecule/default/prepare.yml
  edpm_ansible/roles/edpm_growvols/tasks/main.yml
  edpm_ansible/roles/edpm_growvols/vars/redhat.yml
Labels: approved, lgtm

#84 fix edpm_growvols wrong path
  roles/edpm_growvols/defaults/main.yml
  roles/edpm_growvols/meta/main.yml
  roles/edpm_growvols/molecule/default/converge.yml
  roles/edpm_growvols/molecule/default/molecule.yml
  roles/edpm_growvols/molecule/default/prepare.yml
  roles/edpm_growvols/tasks/main.yml
  roles/edpm_growvols/vars/redhat.yml
Labels: approved, lgtm

#87 Removing obsolete settings from ansible-lint config
  .ansible-lint
Labels: approved, lgtm

#91 Fix wrong documentation link
  roles/edpm_container_manage/files/edpm-container-shutdown-service
Labels: approved, lgtm

#90 Get rid of container healthchecks
  roles/edpm_iscsid/templates/iscsid.yaml.j2
  roles/edpm_logrotate_crond/templates/logrotate_crond.yaml.j2
  roles/edpm_ovn/templates/ovn_controller.yaml.j2
  roles/edpm_ovn/templates/ovn_metadata_agent.yaml.j2
Labels: approved, lgtm
