Repository openstack-k8s-operators/edpm-ansible, pull requests merged in 2023-07, with the labels that each got.

#204 Check if we have required python version available before running tests
  scripts/molecule_venv.sh
Labels: approved, lgtm

#207 Documenting main endpoint of the edpm_tuned role
  roles/edpm_tuned/meta/argument_specs.yml
  roles/edpm_tuned/molecule/isolated/converge.yml
Labels: approved, lgtm

#208 Add tasks to spawn ceilometer-ipmi agent container
  roles/edpm_telemetry/molecule/default/prepare.yml
  roles/edpm_telemetry/tasks/deploy_ceilometer.yml
Labels: approved, lgtm, ok-to-test

#177 Option to select the required DDP package
  roles/edpm_ddp_package/defaults/main.yml
  roles/edpm_ddp_package/meta/argument_specs.yml
  roles/edpm_ddp_package/meta/main.yml
  roles/edpm_ddp_package/molecule/default/converge.yml
  roles/edpm_ddp_package/molecule/default/molecule.yml
  roles/edpm_ddp_package/molecule/default/prepare.yml
  roles/edpm_ddp_package/tasks/main.yml
Labels: approved, lgtm, ok-to-test

#210 Update ee runner image var using set_openstack_containers role
  ci/playbooks/build_runner_image.yaml
Labels: approved, lgtm

#211 Use ansible_hostname rather than fqdn for hostname
  roles/edpm_ovn/defaults/main.yml
Labels: approved, lgtm

#209 Enhance instructions for testing local changes
  README.md
  docs/source/contributing_roles.rst
  docs/source/testing_with_ansibleee.rst
Labels: approved, lgtm

#214 Consolidating edpm_podman arguments
  roles/edpm_podman/defaults/main.yml
  roles/edpm_podman/tasks/buildah_login.yml
  roles/edpm_podman/tasks/install.yml
  roles/edpm_podman/templates/registries.conf.j2
Labels: approved, lgtm

#206 Removing ununsed debug args
  roles/edpm_ceph_client_files/defaults/main.yml
  roles/edpm_chrony/README.rst
  roles/edpm_chrony/defaults/main.yml
  roles/edpm_container_manage/defaults/main.yml
  roles/edpm_container_manage/meta/argument_specs.yml
  roles/edpm_container_manage/molecule/default/converge.yml
  roles/edpm_container_manage/tasks/create.yml
  roles/edpm_container_manage/tasks/delete_orphan.yml
  roles/edpm_container_manage/tasks/main.yml
  roles/edpm_container_standalone/defaults/main.yml
  roles/edpm_hosts_entries/defaults/main.yml
  roles/edpm_logrotate_crond/defaults/main.yml
  roles/edpm_logrotate_crond/molecule/default/converge.yml
  roles/edpm_nodes_validation/defaults/main.yml
  roles/edpm_podman/defaults/main.yml
  roles/edpm_telemetry/tasks/deploy_ceilometer.yml
Labels: approved, lgtm

#220 Add compute-approvers
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm

#219 Add new network template
  roles/edpm_network_config/templates/ci/extracted_crc_nic2_vlans.j2
Labels: approved, lgtm

#218 Limiting pyyaml use in documentation build to stable versions
  docs/docs-requirements.txt
Labels: approved, lgtm

#222 Disable running zuul edpm jobs when irrelevant files are modified
  zuul.d/jobs.yaml
Labels: approved, lgtm

#221 Exclude edpm_ddp_package molecule test from being executed locally
  scripts/test_roles.py
Labels: approved, lgtm

#223 Drop build_runner_image playbook from edpm-ansible
  ci/playbooks/build_runner_image.yaml
  zuul.d/jobs.yaml
Labels: approved, lgtm

#213 Setting argspecs for the edpm_sshd role
  roles/edpm_sshd/meta/argument_specs.yml
Labels: approved, lgtm

#226 Adding note about edpm_ssh_known_hosts not exposing parameters
  roles/edpm_ssh_known_hosts/meta/argument_specs.yml
Labels: approved, lgtm

#225 Use edpm_network_config_override when defined
  roles/edpm_network_config/defaults/main.yml
  roles/edpm_network_config/molecule/default/converge.yml
  roles/edpm_network_config/tasks/os_net_config.yml
Labels: approved

#237 Revert "Use edpm_network_config_override when defined"
  roles/edpm_network_config/defaults/main.yml
  roles/edpm_network_config/molecule/default/converge.yml
  roles/edpm_network_config/tasks/os_net_config.yml
Labels: approved, lgtm

#224 Argspecs for edpm_podman role
  roles/edpm_podman/meta/argument_specs.yml
Labels: approved, lgtm, argspecs

#229 Setting argspecs for edpm_nodes_validation role
  roles/edpm_nodes_validation/defaults/main.yml
  roles/edpm_nodes_validation/meta/argument_specs.yml
Labels: approved, lgtm, argspecs

#232 Argspec for edpm_kernel role
  roles/edpm_kernel/meta/argument_specs.yml
Labels: approved, lgtm, argspecs

#238 Argspec for edpm_growvols role
  roles/edpm_growvols/meta/argument_specs.yml
Labels: approved, lgtm, argspecs

#241 Argument specs for edpm_container_standalone role
  roles/edpm_container_standalone/defaults/main.yml
  roles/edpm_container_standalone/meta/argument_specs.yml
Labels: approved, lgtm, argspecs

#242 Argument spec for the edpm_chrony role
  roles/edpm_chrony/meta/argument_specs.yml
Labels: approved, lgtm, argspecs

#244 Argspecs for edpm_ceph_client_files
  roles/edpm_ceph_client_files/defaults/main.yml
  roles/edpm_ceph_client_files/meta/argument_specs.yml
Labels: approved, lgtm, argspecs

#245 Finalizing arspecs for edpm_bootstrap
  roles/edpm_bootstrap/meta/argument_specs.yml
Labels: approved, lgtm, argspecs

#227 Arg specs for the edpm_ovn_bgp_agent role
  docs/source/roles/role-edpm_ovn_bgp_agent.rst
  roles/edpm_ovn_bgp_agent/meta/argument_specs.yml
Labels: approved, lgtm, argspecs

#233 Argspec for edpm_iscsid role
  roles/edpm_iscsid/defaults/main.yml
  roles/edpm_iscsid/meta/argument_specs.yml
Labels: approved, lgtm, argspecs
