Repository openstack-k8s-operators/edpm-ansible, pull requests merged in 2023-10, with the labels that each got.

#385 Do not log exclude Ceph containers from podman container list
  roles/edpm_container_manage/tasks/delete_orphan.yml
Labels: approved, lgtm

#375 Add edpm role to deploy Neutron DHCP agent
  playbooks/neutron_dhcp.yaml
  roles/edpm_download_cache/tasks/container_images.yml
  roles/edpm_neutron_dhcp/OWNERS
  roles/edpm_neutron_dhcp/defaults/main.yml
  roles/edpm_neutron_dhcp/files/.gitkeep
  roles/edpm_neutron_dhcp/handlers/main.yml
  roles/edpm_neutron_dhcp/meta/argument_specs.yml
  roles/edpm_neutron_dhcp/meta/main.yml
  roles/edpm_neutron_dhcp/molecule/default/collections.yml
  roles/edpm_neutron_dhcp/molecule/default/converge.yml
  roles/edpm_neutron_dhcp/molecule/default/molecule.yml
  roles/edpm_neutron_dhcp/molecule/default/prepare.yml
  roles/edpm_neutron_dhcp/molecule/default/test-data/10-neutron-dhcp.conf
  roles/edpm_neutron_dhcp/molecule/default/verify.yml
  roles/edpm_neutron_dhcp/tasks/configure.yml
  roles/edpm_neutron_dhcp/tasks/download_cache.yml
  roles/edpm_neutron_dhcp/tasks/install.yml
  roles/edpm_neutron_dhcp/tasks/main.yml
  roles/edpm_neutron_dhcp/tasks/run.yml
  roles/edpm_neutron_dhcp/templates/kolla_config/neutron_dhcp_agent.yaml.j2
  roles/edpm_neutron_dhcp/templates/neutron-dhcp-agent.conf.j2
  roles/edpm_neutron_dhcp/templates/neutron.conf.j2
  roles/edpm_neutron_dhcp/templates/neutron_dhcp_agent.yaml.j2
  roles/edpm_neutron_dhcp/templates/rootwrap.conf.j2
  roles/edpm_neutron_dhcp/vars/main.yml
Labels: approved, lgtm

#386 Speed up Ceph exclude task
  roles/edpm_container_manage/tasks/delete_orphan.yml
Labels: approved, lgtm

#388 Revert "Drop baremetal job"
  zuul.d/projects.yaml
Labels: approved, lgtm

#383 Add frr and ovn_bgp_agent images to download_cache
  roles/edpm_download_cache/tasks/container_images.yml
  roles/edpm_frr/defaults/main.yml
  roles/edpm_frr/meta/argument_specs.yml
  roles/edpm_frr/tasks/download_cache.yml
  roles/edpm_ovn_bgp_agent/defaults/main.yml
  roles/edpm_ovn_bgp_agent/meta/argument_specs.yml
  roles/edpm_ovn_bgp_agent/tasks/download_cache.yml
Labels: approved, lgtm, ok-to-test

#389 Ensure logrotate image is also pre-downloaded
  roles/edpm_download_cache/tasks/container_images.yml
  roles/edpm_download_cache/tasks/packages.yml
  roles/edpm_logrotate_crond/tasks/download_cache_images.yml
  roles/edpm_logrotate_crond/tasks/download_cache_packages.yml
  roles/edpm_ovn_bgp_agent/tasks/download_cache.yml
Labels: approved, lgtm, ok-to-test

#395 Make `edpm_ceph_client_files` role compliant with ansible-lint production profile
  roles/edpm_ceph_client_files/tasks/main.yml
Labels: approved, lgtm, enforce-production-linting-profile

#405 install systemd-containerd on all edpm hosts as part of bootstrap
  roles/edpm_bootstrap/defaults/main.yml
  roles/edpm_bootstrap/meta/argument_specs.yml
Labels: approved, lgtm

#404 Make `edpm_growvols` role compliant with ansible-lint `production` profile
  roles/edpm_growvols/tasks/main.yml
Labels: approved, lgtm, enforce-production-linting-profile

#398 Make `edpm_container_rm` role compliant with ansible-lint `production` profile
  roles/edpm_container_rm/tasks/edpm_podman_container_rm.yml
Labels: approved, lgtm, enforce-production-linting-profile

#402 Make `edpm_download_cache` role compliant with ansible-lint `production` profile
  roles/edpm_download_cache/tasks/packages.yml
Labels: approved, lgtm, enforce-production-linting-profile

#393 Make playbooks compliant with ansible-lint `production` profile
  playbooks/ceph_client.yml
  playbooks/ceph_hci_pre.yml
  playbooks/configure_frr.yaml
  playbooks/configure_frr.yml
  playbooks/configure_network.yml
  playbooks/configure_os.yml
  playbooks/configure_ovn_bgp_agent.yml
  playbooks/download_cache.yml
  playbooks/install_frr.yml
  playbooks/install_os.yml
  playbooks/install_ovn_bgp_agent.yml
  playbooks/libvirt.yml
  playbooks/neutron_dhcp.yml
  playbooks/neutron_sriov.yml
  playbooks/nova.yml
  playbooks/ovn.yml
  playbooks/run_frr.yml
  playbooks/run_os.yml
  playbooks/run_ovn_bgp_agent.yml
  playbooks/select_kernel_ddp_package.yml
  playbooks/telemetry.yml
  playbooks/validate_network.yml
Labels: approved, lgtm, enforce-production-linting-profile

#397 Make `edpm_container_manage` role compliant with ansible-lint production profile
  roles/edpm_container_manage/tasks/create.yml
  roles/edpm_container_manage/tasks/main.yml
Labels: approved, lgtm, enforce-production-linting-profile

#400 Make `edpm_container_standalone` role compliant with ansible-lint `production` profile
  roles/edpm_container_standalone/meta/argument_specs.yml
  roles/edpm_container_standalone/tasks/main.yml
  roles/edpm_container_standalone/vars/main.yml
Labels: approved, lgtm, enforce-production-linting-profile

#403 Make `edpm_frr` role compliant with ansible-lint `production` profile
  roles/edpm_frr/meta/argument_specs.yml
  roles/edpm_frr/meta/main.yml
  roles/edpm_frr/tasks/configure.yml
  roles/edpm_frr/tasks/install.yml
Labels: approved, lgtm, enforce-production-linting-profile

#391 Make `edpm_bootstrap` role compliant with ansible-lint `production` profile
  roles/edpm_bootstrap/handlers/main.yml
  roles/edpm_bootstrap/tasks/bootstrap.yml
  roles/edpm_bootstrap/tasks/main.yml
  roles/edpm_bootstrap/tasks/packages.yml
  roles/edpm_bootstrap/tasks/swap.yml
Labels: approved, lgtm, enforce-production-linting-profile

#412 [doc]Fix repo setup command
  docs/source/testing_roles.rst
Labels: approved, lgtm

#408 Make `edpm_kernel` compliant with ansible-lint `production` profile
  roles/edpm_kernel/handlers/main.yml
  roles/edpm_kernel/tasks/kernelargs.yml
  roles/edpm_kernel/tasks/main.yml
Labels: approved, lgtm

#415 Added missing `become:true` in `edpm_bootstrap` handlers tasks
  roles/edpm_bootstrap/handlers/main.yml
Labels: approved, lgtm

#396 Make `edpm_chrony` role compliant with ansible-lint `production` profile
  roles/edpm_chrony/README.rst
  roles/edpm_chrony/tasks/config.yml
  roles/edpm_chrony/tasks/online.yml
  roles/edpm_chrony/tasks/sync.yml
  roles/edpm_chrony/tests/all.yml
  roles/edpm_chrony/tests/config.yml
  roles/edpm_chrony/tests/install.yml
  roles/edpm_chrony/tests/inventory.yml
  roles/edpm_chrony/tests/upgrade.yml
Labels: approved, lgtm, enforce-production-linting-profile

#416 s/with_items/loop/g
  molecule/common/test_deps/tasks/main.yml
  roles/edpm_container_rm/molecule/default/prepare.yml
  roles/edpm_container_rm/molecule/podman-rm-stopped/prepare.yml
  roles/edpm_frr/tasks/install.yml
  roles/edpm_kernel/tasks/reboot.yaml
  roles/edpm_libvirt/molecule/default/verify.yml
  roles/edpm_libvirt/tasks/configure.yml
  roles/edpm_libvirt/tasks/install.yml
  roles/edpm_neutron_dhcp/molecule/default/verify.yml
  roles/edpm_neutron_dhcp/tasks/configure.yml
  roles/edpm_neutron_dhcp/tasks/install.yml
  roles/edpm_neutron_sriov/molecule/default/verify.yml
  roles/edpm_neutron_sriov/tasks/configure.yml
  roles/edpm_neutron_sriov/tasks/install.yml
  roles/edpm_nova/molecule/default/verify.yml
  roles/edpm_nova/tasks/configure.yml
  roles/edpm_ovn/molecule/default/verify.yml
  roles/edpm_ovn/tasks/configure.yml
  roles/edpm_ovn_bgp_agent/tasks/install.yml
  roles/edpm_podman/molecule/default/prepare.yml
  roles/edpm_users/molecule/default/verify.yml
  roles/edpm_users/tasks/main.yml
Labels: approved, lgtm

#390 Molecule improvement
  .github/workflows/molecule.yaml
  roles/edpm_growvols/molecule/default/molecule.yml
  roles/edpm_multipathd/molecule/default/prepare.yml
  roles/edpm_nvdimm/molecule/default/collections.yml
  roles/edpm_nvdimm/molecule/default/molecule.yml
  roles/edpm_nvdimm/molecule/default/prepare.yml
  scripts/test_roles.py
Labels: approved, lgtm

#401 Make `edpm_ddp_package` role compliant with ansible-lint `production` profile
  roles/edpm_ddp_package/meta/main.yml
  roles/edpm_ddp_package/tasks/main.yml
Labels: approved, lgtm, enforce-production-linting-profile

#414 [edpm_ssh_known_hosts]Support multiple host key types
  roles/edpm_ssh_known_hosts/molecule/default/converge.yml
  roles/edpm_ssh_known_hosts/molecule/default/tests/test_default.py
  roles/edpm_ssh_known_hosts/tasks/main.yml
Labels: approved, lgtm

#419 Make `edpm_modules_load` compliant with ansible-lint `production` profile
  roles/edpm_module_load/tasks/main.yml
Labels: approved, lgtm, enforce-production-linting-profile

#422 [edpm_ssh_known_hosts]Fix hostname pattern
  roles/edpm_ssh_known_hosts/molecule/default/tests/test_default.py
  roles/edpm_ssh_known_hosts/molecule/no_networks/tests/test_no_networks.py
  roles/edpm_ssh_known_hosts/tasks/main.yml
Labels: approved, lgtm

#423 Make `edpm_neutron_dhcp` role compliant with ansible-lint `production` profile
  roles/edpm_neutron_dhcp/defaults/main.yml
  roles/edpm_neutron_dhcp/handlers/main.yml
  roles/edpm_neutron_dhcp/tasks/configure.yml
  roles/edpm_neutron_dhcp/tasks/install.yml
Labels: approved, lgtm, enforce-production-linting-profile

#426 use correct ceph host dir for libvirt and nova
  roles/edpm_libvirt/molecule/default/prepare.yml
  roles/edpm_libvirt/molecule/default/verify.yml
  roles/edpm_libvirt/tasks/install.yml
  roles/edpm_libvirt/templates/libvirt_virtqemud/libvirt_virtqemud.json.j2
  roles/edpm_nova/molecule/default/prepare.yml
  roles/edpm_nova/molecule/default/verify.yml
  roles/edpm_nova/templates/nova_compute.json.j2
Labels: approved, lgtm

#427 Make `edpm_neutron_sriov` role compliant with ansible-lint `production` profile
  roles/edpm_neutron_sriov/handlers/main.yml
  roles/edpm_neutron_sriov/tasks/configure.yml
  roles/edpm_neutron_sriov/tasks/install.yml
Labels: approved, lgtm, enforce-production-linting-profile

#421 Make `edpm_network_config` role compliant with ansible-lint `production` profile
  roles/edpm_network_config/tasks/main.yml
  roles/edpm_network_config/tasks/network_config.yml
Labels: approved, lgtm, enforce-production-linting-profile

#418 Make `edpm_logrotate_crond` role compliant with ansible-lint `production` profile
  roles/edpm_logrotate_crond/files/logrotate_crond.yaml
  roles/edpm_logrotate_crond/meta/argument_specs.yml
  roles/edpm_logrotate_crond/tasks/configure.yml
Labels: approved, lgtm, enforce-production-linting-profile

#430 Make `edpm_nodes_validation` role compliant with ansible-lint `production` profile
  roles/edpm_nodes_validation/tasks/ping.yml
Labels: approved, lgtm, enforce-production-linting-profile

#432 Update testing_with_ansibleee example for OpenStackDataPlaneNodeSet
  docs/source/testing_with_ansibleee.rst
Labels: approved, lgtm

#409 Fix owner of the /var/lib/openstack created by the neutron_dhcp role
  roles/edpm_neutron_dhcp/tasks/install.yml
Labels: approved, lgtm

#431 Fixed typo while using `ansible.builtin.service_facts` in `edpm_multipathd` role
  roles/edpm_multipathd/tasks/install.yml
Labels: approved, lgtm

#434 Make `edpm_ovn_bgp_agent` role compliant with ansible-lint `production` profile
  roles/edpm_ovn_bgp_agent/meta/argument_specs.yml
  roles/edpm_ovn_bgp_agent/meta/main.yml
  roles/edpm_ovn_bgp_agent/tasks/configure.yml
Labels: approved, lgtm, enforce-production-linting-profile

#406 Remove neutron-cleanup service
  roles/edpm_ovn/files/neutron-cleanup
  roles/edpm_ovn/files/neutron-cleanup.service
  roles/edpm_ovn/tasks/install.yml
Labels: approved, lgtm

#429 [edpm_ssh_known_hosts] Add back hostname globbing
  roles/edpm_ssh_known_hosts/molecule/default/tests/test_default.py
  roles/edpm_ssh_known_hosts/molecule/no_networks/tests/test_no_networks.py
  roles/edpm_ssh_known_hosts/tasks/main.yml
Labels: approved, lgtm

#433 Make `edpm_ovn` compliant with ansible-lint `production` profile
  roles/edpm_ovn/defaults/main.yml
  roles/edpm_ovn/meta/argument_specs.yml
  roles/edpm_ovn/tasks/cleanup.yml
  roles/edpm_ovn/tasks/configure.yml
  roles/edpm_ovn/tasks/firewall.yml
Labels: approved, lgtm, enforce-production-linting-profile

#435 Make `edpm_podman` role compliant with ansible-lint `production` profile
  roles/edpm_podman/handlers/main.yml
  roles/edpm_podman/meta/argument_specs.yml
  roles/edpm_podman/tasks/buildah_login.yml
  roles/edpm_podman/tasks/configure.yml
  roles/edpm_podman/tasks/install.yml
  roles/edpm_podman/tasks/login.yml
  roles/edpm_podman/tasks/purge.yml
  roles/edpm_podman/tasks/rsyslog.yml
  roles/edpm_podman/tasks/rsyslog_cleanup.yml
Labels: approved, lgtm, enforce-production-linting-profile

#438 [edpm_ssh_known_hosts]Support non standard ssh port
  roles/edpm_ssh_known_hosts/molecule/default/molecule.yml
  roles/edpm_ssh_known_hosts/molecule/default/tests/test_default.py
  roles/edpm_ssh_known_hosts/tasks/main.yml
Labels: approved, lgtm

#428 Make `edpm_nftables` role compliant with ansible-lint `production` profile`
  roles/edpm_nftables/files/00-base-rules.yaml
  roles/edpm_nftables/tasks/cleanup.yml
  roles/edpm_nftables/tasks/configure.yml
  roles/edpm_nftables/tasks/run.yml
  roles/edpm_nftables/tasks/service-bootstrap.yml
Labels: approved, lgtm, enforce-production-linting-profile

#411 New zuul job for edpm_frr role
  .github/workflows/molecule.yaml
  roles/edpm_frr/molecule/default/converge.yml
  roles/edpm_frr/molecule/default/molecule.yml
  roles/edpm_frr/molecule/default/prepare.yml
  roles/edpm_frr/tasks/install.yml
  zuul.d/jobs.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#447 Execute `Ensure legacy iptables services are off` task only if iptables and ip6tables services are present
  roles/edpm_nftables/tasks/service-bootstrap.yml
Labels: approved, lgtm

#450 Fixed systemd checks for non existent services
  roles/edpm_bootstrap/tasks/bootstrap.yml
  roles/edpm_chrony/tasks/install.yml
  roles/edpm_multipathd/tasks/install.yml
  roles/edpm_nftables/tasks/service-bootstrap.yml
Labels: approved, lgtm

#439 Make `edpm_telemetry` role compliant with ansible-lint `production` profile
  roles/edpm_telemetry/tasks/deploy_ceilometer.yml
Labels: approved, lgtm, enforce-production-linting-profile

#449 [edpm_ssh_known_hosts]Ensure host IP is added
  roles/edpm_ssh_known_hosts/tasks/main.yml
Labels: approved, lgtm

#442 Make `edpm_users` role compliant with ansible-lint `production` profile
  roles/edpm_users/meta/argument_specs.yml
  roles/edpm_users/tasks/create_users_and_groups.yml
  roles/edpm_users/tasks/main.yml
Labels: approved, lgtm, enforce-production-linting-profile

#445 [nova]Add nova user to the EDPM host
  roles/edpm_nova/molecule/default/verify.yml
  roles/edpm_nova/tasks/configure.yml
Labels: approved, lgtm

#448 [edpm_ssh_known_hosts]Cleanup unused code paths
  roles/edpm_ssh_known_hosts/molecule/default/molecule.yml
  roles/edpm_ssh_known_hosts/molecule/default/tests/test_default.py
  roles/edpm_ssh_known_hosts/tasks/main.yml
Labels: approved, lgtm

#452 Fix YAML errors in `plugins/filter` documentation files
  plugins/filter/dict_to_list.yml
  plugins/filter/haskey.yml
  plugins/filter/jump_chain_targets.yml
  plugins/filter/needs_delete.yml
Labels: approved, lgtm, enforce-production-linting-profile

#453 Fix trivial YAML errors in several roles
  roles/edpm_chrony/meta/main.yml
  roles/edpm_network_config/tasks/main.yml
  roles/edpm_network_config/tasks/network_config.yml
  roles/edpm_ovn_bgp_agent/defaults/main.yml
  roles/edpm_sshd/tasks/install.yml
Labels: approved, lgtm, enforce-production-linting-profile

#454 [molecule]Fix known_hosts molecule test
  roles/edpm_ssh_known_hosts/molecule/default/tests/test_default.py
Labels: approved, lgtm

#437 Make `edpm_ssh_known_hosts` role compliant with ansible-lint `production` profile
  roles/edpm_ssh_known_hosts/tasks/main.yml
Labels: approved, lgtm, enforce-production-linting-profile

#407 Make `edpm_iscsid` role compliant with ansible-lint `production` profile
  roles/edpm_iscsid/handlers/main.yml
  roles/edpm_iscsid/tasks/configure.yml
  roles/edpm_iscsid/tasks/install.yml
Labels: approved, lgtm, enforce-production-linting-profile

#458 Fix "Too many spaces inside braces" YAML error
  roles/edpm_frr/tasks/install.yml
  roles/edpm_iscsid/tasks/install.yml
  roles/edpm_libvirt/tasks/configure.yml
  roles/edpm_libvirt/tasks/install.yml
  roles/edpm_multipathd/tasks/configure.yml
  roles/edpm_neutron_dhcp/tasks/install.yml
  roles/edpm_neutron_sriov/tasks/install.yml
  roles/edpm_nova/tasks/configure.yml
  roles/edpm_ovn_bgp_agent/tasks/install.yml
  roles/edpm_telemetry/tasks/deploy_ceilometer.yml
  roles/edpm_users/defaults/main.yml
  roles/edpm_users/meta/argument_specs.yml
Labels: approved, lgtm, enforce-production-linting-profile

#444 Adding edpm_iscsid molecule job
  .github/workflows/molecule.yaml
  roles/edpm_iscsid/molecule/default/converge.yml
  roles/edpm_iscsid/molecule/default/molecule.yml
  roles/edpm_iscsid/molecule/default/prepare.yml
  zuul.d/jobs.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#456 Make the collection meta files compliant with ansible-lint `production` profile
  CHANGELOG.md
  galaxy.yml
  meta/runtime.yml
Labels: approved, lgtm, enforce-production-linting-profile

#392 Enforce `production` profile in ansible-lint
  .ansible-lint
Labels: approved, lgtm, enforce-production-linting-profile

#459 Add `galaxy[version-incorrect]` to ansible-lint skip-list
  .ansible-lint
Labels: approved, lgtm, enforce-production-linting-profile

#460 Version bump `ansible-lint` to `v6.20.3` and enforce `ansible-core` version requirement
  .pre-commit-config.yaml
Labels: approved, lgtm, enforce-production-linting-profile

#464 Clean frr and ovn-bgp-agent playbooks into one
  playbooks/configure_frr.yml
  playbooks/configure_ovn_bgp_agent.yml
  playbooks/install_frr.yml
  playbooks/install_ovn_bgp_agent.yml
  playbooks/run_frr.yml
  playbooks/run_ovn_bgp_agent.yml
Labels: approved, lgtm, ok-to-test

#461 CI testing for edpm_ovn_bgp_agent role
  .github/workflows/molecule.yaml
  roles/edpm_ovn_bgp_agent/molecule/default/converge.yml
  roles/edpm_ovn_bgp_agent/molecule/default/molecule.yml
  roles/edpm_ovn_bgp_agent/molecule/default/prepare.yml
  zuul.d/jobs.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#462 Moved roles from `configure_network.yml` playbook to `bootstrap.yml` playbook
  playbooks/bootstrap.yml
  playbooks/configure_network.yml
Labels: approved, lgtm

#446 [nova]Set up ssh keys auth for the nova user
  roles/edpm_nova/molecule/default/prepare.yml
  roles/edpm_nova/molecule/default/test-data/migration-key/ssh-privatekey
  roles/edpm_nova/molecule/default/test-data/migration-key/ssh-publickey
  roles/edpm_nova/molecule/default/verify.yml
  roles/edpm_nova/tasks/configure.yml
  roles/edpm_nova/templates/config.json.j2
  roles/edpm_nova/templates/nova_compute.json.j2
  roles/edpm_nova/templates/ssh-config
Labels: approved, lgtm

#471 Adding edpm_users molecule tests to the CI
  .github/workflows/molecule.yaml
Labels: approved, lgtm

#463 Add role to setup neutron ovn agent
  .github/workflows/molecule.yaml
  playbooks/neutron_ovn.yaml
  roles/edpm_download_cache/tasks/container_images.yml
  roles/edpm_neutron_ovn/OWNERS
  roles/edpm_neutron_ovn/defaults/main.yml
  roles/edpm_neutron_ovn/meta/argument_specs.yml
  roles/edpm_neutron_ovn/meta/main.yml
  roles/edpm_neutron_ovn/molecule/default/collections.yml
  roles/edpm_neutron_ovn/molecule/default/converge.yml
  roles/edpm_neutron_ovn/molecule/default/molecule.yml
  roles/edpm_neutron_ovn/molecule/default/prepare.yml
  roles/edpm_neutron_ovn/molecule/default/test-data/10-neutron-ovn.conf
  roles/edpm_neutron_ovn/molecule/default/verify.yml
  roles/edpm_neutron_ovn/tasks/bootstrap.yml
  roles/edpm_neutron_ovn/tasks/configure.yml
  roles/edpm_neutron_ovn/tasks/download_cache.yml
  roles/edpm_neutron_ovn/tasks/install.yml
  roles/edpm_neutron_ovn/tasks/main.yml
  roles/edpm_neutron_ovn/tasks/run.yml
  roles/edpm_neutron_ovn/templates/kolla_ovn_agent.yaml.j2
  roles/edpm_neutron_ovn/templates/neutron-ovn-agent.conf.j2
  roles/edpm_neutron_ovn/templates/ovn_agent.yaml.j2
  roles/edpm_neutron_ovn/templates/rootwrap.conf.j2
Labels: approved, lgtm

#475 Setting default value of the user
  roles/edpm_neutron_dhcp/tasks/install.yml
Labels: approved, lgtm

#476 Add slawqo to network-approvers group
  OWNERS_ALIASES
  roles/edpm_neutron_dhcp/OWNERS
  roles/edpm_neutron_metadata/OWNERS
  roles/edpm_neutron_ovn/OWNERS
  roles/edpm_neutron_sriov/OWNERS
  roles/edpm_ovn/OWNERS
Labels: approved, lgtm

#466 [edpm_libvirt]Add libvirt user to the EDPM host
  roles/edpm_libvirt/molecule/default/verify.yml
  roles/edpm_libvirt/tasks/main.yml
  roles/edpm_libvirt/tasks/user.yml
Labels: approved, lgtm

#468 Adding edpm_download_cache to CI
  .github/workflows/molecule.yaml
  roles/edpm_download_cache/molecule/default/molecule.yml
  roles/edpm_download_cache/molecule/molecule_config.yaml
  scripts/test_roles.py
Labels: approved, lgtm

#469 [edpm_users]Add support for adding user to groups
  roles/edpm_users/molecule/default/converge.yml
  roles/edpm_users/molecule/default/verify.yml
  roles/edpm_users/tasks/create_users_and_groups.yml
Labels: approved, lgtm

#470 [edpm_nova]Add nova user to libvirt group
  roles/edpm_nova/molecule/default/verify.yml
  roles/edpm_nova/tasks/configure.yml
Labels: approved, lgtm

#479 Update CR name on NFS docs
  docs/source/testing_with_ansibleee.rst
Labels: approved, lgtm

#480 Minor improvements on NFS docs
  docs/source/testing_with_ansibleee.rst
Labels: approved, lgtm

#457 use correct ceph host dir for libvirt and nova
  roles/edpm_libvirt/molecule/default/prepare.yml
  roles/edpm_libvirt/molecule/default/verify.yml
  roles/edpm_libvirt/tasks/install.yml
  roles/edpm_libvirt/templates/libvirt_virtqemud/libvirt_virtqemud.json.j2
  roles/edpm_nova/molecule/default/prepare.yml
  roles/edpm_nova/molecule/default/verify.yml
  roles/edpm_nova/templates/nova_compute.json.j2
Labels: approved, lgtm

#394 Sidecar containers in neutron agents
  .github/workflows/molecule.yaml
  roles/edpm_neutron_dhcp/defaults/main.yml
  roles/edpm_neutron_dhcp/meta/argument_specs.yml
  roles/edpm_neutron_dhcp/molecule/default/converge.yml
  roles/edpm_neutron_dhcp/molecule/default/molecule.yml
  roles/edpm_neutron_dhcp/molecule/default/prepare.yml
  roles/edpm_neutron_dhcp/molecule/default/tests/test_neutron_dhcp.py
  roles/edpm_neutron_dhcp/molecule/default/verify.yml
  roles/edpm_neutron_dhcp/tasks/configure.yml
  roles/edpm_neutron_dhcp/tasks/install.yml
  roles/edpm_neutron_dhcp/templates/neutron_dhcp_agent.yaml.j2
  roles/edpm_neutron_dhcp/templates/wrappers/common_part.j2
  roles/edpm_neutron_dhcp/templates/wrappers/dnsmasq.j2
  roles/edpm_neutron_dhcp/templates/wrappers/haproxy.j2
  roles/edpm_neutron_dhcp/templates/wrappers/kill-script.j2
  roles/edpm_neutron_dhcp/templates/wrappers/kill-script_common_part.j2
  roles/edpm_neutron_metadata/defaults/main.yml
  roles/edpm_neutron_metadata/meta/argument_specs.yml
  roles/edpm_neutron_metadata/molecule/default/converge.yml
  roles/edpm_neutron_metadata/molecule/default/molecule.yml
  roles/edpm_neutron_metadata/molecule/default/prepare.yml
  roles/edpm_neutron_metadata/molecule/default/test-data/10-neutron-metadata.conf
  roles/edpm_neutron_metadata/molecule/default/tests/test_neutron_metadata.py
  roles/edpm_neutron_metadata/molecule/default/verify.yml
  roles/edpm_neutron_metadata/tasks/install.yml
  roles/edpm_neutron_metadata/templates/ovn_metadata_agent.yaml.j2
  roles/edpm_neutron_metadata/templates/wrappers/common_part.j2
  roles/edpm_neutron_metadata/templates/wrappers/haproxy.j2
  roles/edpm_neutron_metadata/templates/wrappers/kill-script.j2
  roles/edpm_neutron_metadata/templates/wrappers/kill-script_common_part.j2
Labels: approved, lgtm

#481 Fix molecule `default` scenario for `edpm_network_config` role
  roles/edpm_network_config/molecule/default/converge.yml
Labels: approved, lgtm

#473 Adding molecule tests for edpm_ddp_package role to local and CI
  .github/workflows/molecule.yaml
  scripts/test_roles.py
Labels: approved, lgtm

#425 ovn: don't explicitly set vlan-limit=0
  roles/edpm_ovn/defaults/main.yml
  roles/edpm_ovn/meta/argument_specs.yml
  roles/edpm_ovn/tasks/configure.yml
Labels: approved, lgtm

#482 [neutron_metadata] Add missing mount
  roles/edpm_neutron_dhcp/defaults/main.yml
  roles/edpm_neutron_dhcp/meta/argument_specs.yml
  roles/edpm_neutron_metadata/defaults/main.yml
  roles/edpm_neutron_metadata/meta/argument_specs.yml
Labels: approved, lgtm
