Repository openstack-k8s-operators/edpm-ansible, pull requests merged in 2023-04, with the labels that each got.

#92 Remove logic for docker
  docs/source/roles/role-edpm_container_manage.rst
  roles/edpm_container_manage/files/edpm-container-shutdown
  roles/edpm_container_manage/files/edpm-container-shutdown-service
  roles/edpm_container_rm/tasks/edpm_docker_container_rm.yml
  roles/edpm_podman/defaults/main.yml
  roles/edpm_podman/vars/redhat.yml
Labels: approved, lgtm

#95 Added missing documentation for edpm_growvols role
  docs/source/roles/role-edpm_growvols.rst
Labels: approved, lgtm

#96 Default edpm_ceph_client_files_source to /etc/ceph
  roles/edpm_ceph_client_files/defaults/main.yml
  roles/edpm_ceph_client_files/tasks/main.yml
Labels: approved, lgtm

#38 Add iscsid patches
  roles/edpm_iscsid/defaults/main.yml
  roles/edpm_iscsid/files/iscsid.yaml
  roles/edpm_iscsid/tasks/configure.yml
  roles/edpm_iscsid/tasks/install.yml
  roles/edpm_iscsid/tasks/run.yml
Labels: approved, lgtm

#98 Clean dnf/yum cache
  openstack_ansibleee/Dockerfile
Labels: approved, lgtm

#100 edpm_ovn: external_ids ovn-chassis-mac-mappings
  roles/edpm_ovn/defaults/main.yml
Labels: approved, lgtm

#101 Run molecule tests locally in sequence
  Makefile
  scripts/test_roles.py
Labels: approved, lgtm

#110 Get rid of tenacity
  openstack_ansibleee/Dockerfile
  plugins/action/container_systemd.py
  requirements.txt
Labels: approved, lgtm

#97 Initial support for frr and ovn_bgp-agent at EDPM
  playbooks/deploy_edpm_os_configure.yml
  playbooks/deploy_edpm_os_install.yml
  playbooks/deploy_edpm_os_run.yml
  roles/edpm_frr/defaults/main.yml
  roles/edpm_frr/meta/main.yml
  roles/edpm_frr/tasks/configure.yml
  roles/edpm_frr/tasks/install.yml
  roles/edpm_frr/tasks/main.yml
  roles/edpm_frr/tasks/run.yml
  roles/edpm_frr/templates/daemons.j2
  roles/edpm_frr/templates/frr.conf.j2
  roles/edpm_frr/templates/frr.yaml.j2
  roles/edpm_frr/templates/kolla_config/frr.yaml.j2
  roles/edpm_network_config/templates/single_nic_vlans/single_nic_vlans_bgp.j2
  roles/edpm_ovn_bgp_agent/defaults/main.yml
  roles/edpm_ovn_bgp_agent/meta/main.yml
  roles/edpm_ovn_bgp_agent/tasks/configure.yml
  roles/edpm_ovn_bgp_agent/tasks/install.yml
  roles/edpm_ovn_bgp_agent/tasks/main.yml
  roles/edpm_ovn_bgp_agent/tasks/run.yml
  roles/edpm_ovn_bgp_agent/templates/kolla_config/ovn_bgp_agent.yaml.j2
  roles/edpm_ovn_bgp_agent/templates/ovn-bgp-agent.conf.j2
  roles/edpm_ovn_bgp_agent/templates/ovn_bgp_agent.yaml.j2
Labels: approved, lgtm, needs-ok-to-test

#113 Removing the requirements.txt
  .github/workflows/documentation.yaml
  docs/build-docs.sh
  requirements.txt
Labels: approved, lgtm

#111 Adding skiplist and exception recovery for molecule script
  Makefile
  scripts/molecule_venv.sh
  scripts/test_roles.py
Labels: approved, lgtm

#114 Remove ansible-requirements.txt
  ansible-requirements.txt
  galaxy.yml
  zuul.d/playbooks/pre.yml
Labels: approved, lgtm

#115 Remove WIP from README
  README.rst
Labels: approved, lgtm

#116 Molecule/common containerfile
  galaxy.yml
  molecule/common/Containerfile.j2
  roles/edpm_bootstrap/molecule/default/Dockerfile.j2
  roles/edpm_bootstrap/molecule/default/molecule.yml
  roles/edpm_container_manage/molecule/default/Dockerfile.j2
  roles/edpm_container_manage/molecule/default/molecule.yml
  roles/edpm_container_rm/molecule/default/Dockerfile.j2
  roles/edpm_container_rm/molecule/default/molecule.yml
  roles/edpm_container_rm/molecule/podman-rm-stopped/Dockerfile.j2
  roles/edpm_container_rm/molecule/podman-rm-stopped/molecule.yml
  roles/edpm_container_standalone/molecule/default/Dockerfile.j2
  roles/edpm_container_standalone/molecule/default/molecule.yml
  roles/edpm_hosts_entries/molecule/default/Dockerfile.j2
  roles/edpm_hosts_entries/molecule/default/molecule.yml
  roles/edpm_iscsid/molecule/default/Dockerfile.j2
  roles/edpm_iscsid/molecule/default/molecule.yml
  roles/edpm_logrotate_crond/molecule/default/Dockerfile.j2
  roles/edpm_logrotate_crond/molecule/default/molecule.yml
  roles/edpm_network_config/molecule/default/Dockerfile.j2
  roles/edpm_network_config/molecule/default/molecule.yml
  roles/edpm_nftables/molecule/action/Dockerfile.j2
  roles/edpm_nftables/molecule/action/molecule.yml
  roles/edpm_nftables/molecule/default/Dockerfile.j2
  roles/edpm_nftables/molecule/default/molecule.yml
  roles/edpm_nftables/molecule/destination/Dockerfile.j2
  roles/edpm_nftables/molecule/destination/molecule.yml
  roles/edpm_nftables/molecule/source/Dockerfile.j2
  roles/edpm_nftables/molecule/source/molecule.yml
  roles/edpm_nftables/molecule/update_rules/Dockerfile.j2
  roles/edpm_nftables/molecule/update_rules/molecule.yml
  roles/edpm_nodes_validation/molecule/default/Dockerfile.j2
  roles/edpm_nodes_validation/molecule/default/molecule.yml
  roles/edpm_ovn/molecule/default/Dockerfile.j2
  roles/edpm_ovn/molecule/default/molecule.yml
  roles/edpm_sshd/molecule/banners/Dockerfile.j2
  roles/edpm_sshd/molecule/banners/molecule.yml
  roles/edpm_sshd/molecule/default/Dockerfile.j2
  roles/edpm_sshd/molecule/default/molecule.yml
  roles/edpm_sshd/molecule/gssapi/Dockerfile.j2
  roles/edpm_sshd/molecule/gssapi/molecule.yml
  roles/edpm_timezone/molecule/default/Dockerfile.j2
  roles/edpm_timezone/molecule/default/molecule.yml
  roles/edpm_tuned/molecule/default/Dockerfile.j2
  roles/edpm_tuned/molecule/isolated/Dockerfile.j2
  roles/edpm_tuned/molecule/isolated/molecule.yml
Labels: approved, lgtm

#118 Adding further instructions about molecule testing on local machines …
  README.rst
Labels: approved, lgtm

#119 Adding collection build and installation action
  .github/workflows/build-collection.yaml
Labels: approved, lgtm

#120 Update resync default value for the agent
  roles/edpm_ovn_bgp_agent/defaults/main.yml
Labels: approved, lgtm, needs-ok-to-test

#122 Add bshepar, kajinamit, rabi to edpm-approvers
  OWNERS_ALIASES
Labels: approved, lgtm

#123 Remove vars for RHEL/CentOS 8
  roles/edpm_bootstrap/defaults/main.yml
  roles/edpm_bootstrap/vars/redhat-9.yml
  roles/edpm_bootstrap/vars/redhat.yml
  roles/edpm_podman/defaults/main.yml
  roles/edpm_podman/vars/redhat-9.yml
  roles/edpm_podman/vars/redhat.yml
Labels: approved, lgtm

#126 molecule tests for edpm_ssh_knonw_hosts
  roles/edpm_ssh_known_hosts/molecule/default/converge.yml
  roles/edpm_ssh_known_hosts/molecule/default/molecule.yml
  roles/edpm_ssh_known_hosts/molecule/default/prepare.yml
  roles/edpm_ssh_known_hosts/molecule/default/tests/test_default.py
Labels: bug, approved, lgtm

#127 Add edpm_growvols role to deploy_edpm_pre_network playbook
  playbooks/deploy_edpm_os_install.yml
  playbooks/deploy_edpm_pre_network.yml
Labels: approved, lgtm

#130 Removing unnecessary step in the venv script
  scripts/molecule_venv.sh
Labels: approved, lgtm
