Repository openstack-k8s-operators/edpm-ansible, pull requests merged in 2024-01, with the labels that each got.

#516 Stub documentation for all playbooks
  docs/source/playbooks/bootstrap.rst
  docs/source/playbooks/ceph_client.rst
  docs/source/playbooks/ceph_hci_pre.rst
  docs/source/playbooks/configure_network.rst
  docs/source/playbooks/configure_os.rst
  docs/source/playbooks/configure_ovs_dpdk.rst
  docs/source/playbooks/download_cache.rst
  docs/source/playbooks/frr.rst
  docs/source/playbooks/libvirt.rst
  docs/source/playbooks/neutron_dhcp.rst
  docs/source/playbooks/neutron_metadata.rst
  docs/source/playbooks/neutron_ovn.rst
  docs/source/playbooks/neutron_sriov.rst
  docs/source/playbooks/nova.rst
  docs/source/playbooks/ovn.rst
  docs/source/playbooks/ovn_bgp_agent.rst
  docs/source/playbooks/run_os.rst
  docs/source/playbooks/select_kernel_ddp_package.rst
  docs/source/playbooks/telemetry.rst
  docs/source/playbooks/telemetry_logging.rst
  docs/source/playbooks/validate_network.rst
  playbooks/bootstrap.yml
  playbooks/ceph_client.yml
  playbooks/ceph_hci_pre.yml
  playbooks/configure_network.yml
  playbooks/configure_os.yml
  playbooks/install_os.yml
  playbooks/telemetry.yml
  playbooks/telemetry_logging.yml
  playbooks/validate_network.yml
Labels: approved, lgtm

#528 Clarifying tennant_ip argument
  docs/source/playbooks/ovn.rst
  roles/edpm_ovn/meta/argument_specs.yml
Labels: approved, lgtm

#506 Add libvirt certs
  roles/edpm_libvirt/defaults/main.yml
  roles/edpm_libvirt/meta/argument_specs.yml
  roles/edpm_libvirt/tasks/configure.yml
Labels: approved, lgtm

#527 Asciidocs build procedure
  .github/workflows/documentation.yaml
  .gitignore
  docs/Gemfile
  docs/build-docs.sh
  docs/source/main.adoc
Labels: approved

#529 Network config args
  docs/source/playbooks/configure_network.rst
  docs/source/roles/role-edpm_network_config.rst
  roles/edpm_network_config/meta/argument_specs.yml
Labels: approved, lgtm

#525 Add role edpm_install_certs
  docs/source/playbooks/install_certs.rst
  docs/source/roles/role-edpm_install_certs.rst
  playbooks/install_certs.yml
  roles/edpm_install_certs/meta/argument_specs.yml
  roles/edpm_install_certs/meta/main.yml
  roles/edpm_install_certs/tasks/copy_ca_certs.yaml
  roles/edpm_install_certs/tasks/copy_certs_and_keys.yaml
  roles/edpm_install_certs/tasks/main.yml
  roles/edpm_libvirt/defaults/main.yml
  roles/edpm_libvirt/meta/argument_specs.yml
  roles/edpm_libvirt/tasks/configure.yml
  roles/edpm_nova/defaults/main.yml
  roles/edpm_nova/meta/argument_specs.yml
  roles/edpm_nova/tasks/configure.yml
  roles/edpm_nova/templates/nova_compute.json.j2
Labels: approved, lgtm, do-not-merge/hold, ok-to-test

#533 OVN role arguments refactor
  roles/edpm_ovn/defaults/main.yml
  roles/edpm_ovn/meta/argument_specs.yml
Labels: approved, lgtm

#519 Ceilometer will log to stdout, removing log dir creation
  roles/edpm_telemetry/molecule/default/prepare.yml
  roles/edpm_telemetry/tasks/deploy_ceilometer.yml
Labels: approved, lgtm

#536 Adding code snippets to playbook docs
  docs/source/playbooks/bootstrap.rst
  docs/source/playbooks/ceph_client.rst
  docs/source/playbooks/ceph_hci_pre.rst
  docs/source/playbooks/configure_network.rst
  docs/source/playbooks/configure_os.rst
  docs/source/playbooks/configure_ovs_dpdk.rst
  docs/source/playbooks/download_cache.rst
  docs/source/playbooks/frr.rst
  docs/source/playbooks/install_certs.rst
  docs/source/playbooks/install_os.rst
  docs/source/playbooks/libvirt.rst
  docs/source/playbooks/neutron_dhcp.rst
  docs/source/playbooks/neutron_metadata.rst
  docs/source/playbooks/neutron_ovn.rst
  docs/source/playbooks/neutron_sriov.rst
  docs/source/playbooks/nova.rst
  docs/source/playbooks/ovn.rst
  docs/source/playbooks/ovn_bgp_agent.rst
  docs/source/playbooks/run_os.rst
  docs/source/playbooks/select_kernel_ddp_package.rst
  docs/source/playbooks/telemetry.rst
  docs/source/playbooks/telemetry_logging.rst
  docs/source/playbooks/validate_network.rst
Labels: approved, lgtm

#498 [edpm_nova]Pre-generate compute_id
  roles/edpm_nova/molecule/default/verify.yml
  roles/edpm_nova/tasks/configure.yml
Labels: approved, lgtm

#526 [edpm_kernel] Improve `edpm_kernel_args` search in `/proc/cmdline`
  roles/edpm_kernel/molecule/kernelargs-update-substring/converge.yml
  roles/edpm_kernel/molecule/kernelargs-update-substring/molecule.yml
  roles/edpm_kernel/molecule/kernelargs-update-substring/verify.yml
  roles/edpm_kernel/tasks/kernelargs.yml
Labels: approved, lgtm

#537 [edpm_libvirt]Enable os_enable_vtpm selinux boolean
  roles/edpm_libvirt/molecule/default/prepare.yml
  roles/edpm_libvirt/molecule/default/verify.yml
  roles/edpm_libvirt/tasks/configure.yml
  roles/edpm_nova/molecule/default/prepare.yml
Labels: approved, lgtm

#539 Revert "Peform DNF update on edpm node"
  roles/edpm_bootstrap/tasks/download_cache.yml
  roles/edpm_bootstrap/tasks/main.yml
  roles/edpm_bootstrap/tasks/update_package.yml
Labels: approved, lgtm

#532 edpm ovs
  molecule/test-helpers/verify_sockets_exits.yaml
  playbooks/configure_network.yml
  roles/edpm_bootstrap/defaults/main.yml
  roles/edpm_bootstrap/tasks/bootstrap.yml
  roles/edpm_libvirt/molecule/default/test-helpers/verify_sockets_exits.yaml
  roles/edpm_libvirt/molecule/default/verify.yml
  roles/edpm_ovs/defaults/main.yml
  roles/edpm_ovs/files/.gitkeep
  roles/edpm_ovs/handlers/main.yml
  roles/edpm_ovs/meta/argument_specs.yml
  roles/edpm_ovs/meta/main.yml
  roles/edpm_ovs/molecule/default/README.md
  roles/edpm_ovs/molecule/default/converge.yml
  roles/edpm_ovs/molecule/default/molecule.yml
  roles/edpm_ovs/molecule/default/prepare.yml
  roles/edpm_ovs/molecule/default/verify.yml
  roles/edpm_ovs/molecule/vagrant/README.md
  roles/edpm_ovs/molecule/vagrant/molecule.yml
  roles/edpm_ovs/molecule/vagrant/verify.yml
  roles/edpm_ovs/tasks/download_cache.yml
  roles/edpm_ovs/tasks/install.yml
  roles/edpm_ovs/tasks/main.yml
  roles/edpm_ovs/tasks/user.yml
  roles/edpm_users/defaults/main.yml
  zuul.d/jobs.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#510 Fixing nova permission denied issues
  roles/edpm_neutron_sriov/molecule/default/converge.yml
  roles/edpm_neutron_sriov/tasks/install.yml
  roles/edpm_nova/tasks/install.yml
Labels: approved, lgtm

#540 Create host user and group, if not exists
  roles/edpm_users/tasks/create_users_and_groups.yml
Labels: approved, lgtm

#545 Ensure hugetlbfs group exists
  roles/edpm_ovs/tasks/user.yml
Labels: approved, lgtm

#546 Revert "Ensure hugetlbfs group exists"
  roles/edpm_ovs/tasks/user.yml
Labels: approved, lgtm

#549 Revert "Added downgrade of crun in molecule scenario where podman is …
  roles/edpm_frr/molecule/default/prepare.yml
  roles/edpm_neutron_dhcp/molecule/default/prepare.yml
  roles/edpm_neutron_metadata/molecule/default/prepare.yml
  roles/edpm_neutron_ovn/molecule/default/prepare.yml
  roles/edpm_neutron_sriov/molecule/default/prepare.yml
  roles/edpm_ovn/molecule/default/prepare.yml
  roles/edpm_ovn/molecule/noconfig/prepare.yml
  roles/edpm_ovn_bgp_agent/molecule/default/prepare.yml
Labels: approved, lgtm
