Repository openstack-k8s-operators/edpm-ansible, pull requests merged in 2024-08, with the labels that each got.

#718 Re-introduce a become: true that was previously wrongly removed
  roles/edpm_telemetry/molecule/default/converge.yml
  roles/edpm_telemetry_logging/molecule/default/converge.yml
  roles/edpm_telemetry_logging/tasks/configure.yml
Labels: approved, lgtm

#689 Resolving TODO conditional nova template rendering
  roles/edpm_nova/tasks/install.yml
  roles/edpm_nova/templates/nova_compute.json.j2
Labels: approved, lgtm

#721 Fix default hugepages group
  roles/edpm_extra_mounts/defaults/main.yml
  roles/edpm_extra_mounts/molecule/default/converge.yml
Labels: approved, lgtm

#715 Restoring virt-pki-validate check in molecule test
  roles/edpm_libvirt/molecule/default/verify.yml
  roles/edpm_libvirt/tasks/configure.yml
Labels: approved, lgtm

#724 Fix links for setting nfs server on dev system
  docs/source/testing_with_ansibleee.rst
Labels: approved, lgtm

#730 Moving edpm_tuned molecule test to VM
  .github/workflows/molecule.yaml
  roles/edpm_tuned/molecule/default/molecule.yml
  roles/edpm_tuned/molecule/isolated/molecule.yml
  zuul.d/jobs.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#735 Allow setting Zebra graceful_restart time
  roles/edpm_frr/defaults/main.yml
  roles/edpm_frr/meta/argument_specs.yml
  roles/edpm_frr/templates/daemons.j2
Labels: approved, lgtm

#731 Releasing version constraint to allow versions 2.15.0
  docs/docs-requirements.txt
  meta/runtime.yml
  molecule-requirements.txt
  openstack_ansibleee/Dockerfile
  roles/edpm_bootstrap/molecule/molecule_config.yaml
Labels: approved

#727 Set default authfile location
  roles/edpm_download_cache/defaults/main.yml
  roles/edpm_download_cache/meta/argument_specs.yml
  roles/edpm_download_cache/molecule/default/converge.yml
  roles/edpm_frr/molecule/default/converge.yml
  roles/edpm_frr/tasks/download_cache.yml
  roles/edpm_iscsid/tasks/download_cache.yml
  roles/edpm_logrotate_crond/tasks/download_cache_images.yml
  roles/edpm_multipathd/tasks/download_cache.yml
  roles/edpm_neutron_dhcp/tasks/download_cache.yml
  roles/edpm_neutron_metadata/tasks/download_cache.yml
  roles/edpm_neutron_ovn/tasks/download_cache.yml
  roles/edpm_neutron_sriov/tasks/download_cache.yml
  roles/edpm_nova/tasks/download_cache.yml
  roles/edpm_ovn/tasks/download_cache.yml
  roles/edpm_ovn_bgp_agent/molecule/default/prepare.yml
  roles/edpm_ovn_bgp_agent/tasks/download_cache.yml
  roles/edpm_podman/defaults/main.yml
  roles/edpm_podman/meta/argument_specs.yml
  roles/edpm_podman/tasks/buildah_login.yml
  roles/edpm_podman/tasks/login-kube-registry.yml
  roles/edpm_podman/tasks/login.yml
  roles/edpm_swift/tasks/download_cache.yml
  roles/edpm_telemetry/tasks/download_cache.yml
Labels: approved, lgtm

#738 Releasing version constraint to allow versions >= 2.15.0
  docs/docs-requirements.txt
  meta/runtime.yml
  molecule-requirements.txt
  openstack_ansibleee/Dockerfile
  roles/edpm_bootstrap/molecule/molecule_config.yaml
Labels: approved, lgtm

#739 Set explicit podman auth_file location
  roles/edpm_download_cache/defaults/main.yml
  roles/edpm_download_cache/meta/argument_specs.yml
  roles/edpm_download_cache/molecule/default/converge.yml
  roles/edpm_frr/molecule/default/converge.yml
  roles/edpm_frr/tasks/download_cache.yml
  roles/edpm_iscsid/tasks/download_cache.yml
  roles/edpm_logrotate_crond/tasks/download_cache_images.yml
  roles/edpm_multipathd/tasks/download_cache.yml
  roles/edpm_neutron_dhcp/tasks/download_cache.yml
  roles/edpm_neutron_metadata/tasks/download_cache.yml
  roles/edpm_neutron_ovn/tasks/download_cache.yml
  roles/edpm_neutron_sriov/tasks/download_cache.yml
  roles/edpm_nova/tasks/download_cache.yml
  roles/edpm_ovn/tasks/download_cache.yml
  roles/edpm_ovn_bgp_agent/molecule/default/prepare.yml
  roles/edpm_ovn_bgp_agent/tasks/download_cache.yml
  roles/edpm_podman/defaults/main.yml
  roles/edpm_podman/meta/argument_specs.yml
  roles/edpm_podman/tasks/buildah_login.yml
  roles/edpm_podman/tasks/login-kube-registry.yml
  roles/edpm_podman/tasks/login.yml
  roles/edpm_swift/tasks/download_cache.yml
Labels: approved, lgtm

#740 [edpm_kernel] Improved kernel args block conditions
  roles/edpm_kernel/molecule/kernelargs-update-substring/converge.yml
  roles/edpm_kernel/molecule/kernelargs-update-substring/test_vars.yml
  roles/edpm_kernel/molecule/kernelargs-update-substring/verify.yml
  roles/edpm_kernel/tasks/kernelargs.yml
Labels: approved, lgtm

#741 [edpm_kernel] Improved kernel args block conditions
  roles/edpm_kernel/molecule/kernelargs-update-substring/converge.yml
  roles/edpm_kernel/molecule/kernelargs-update-substring/test_vars.yml
  roles/edpm_kernel/molecule/kernelargs-update-substring/verify.yml
  roles/edpm_kernel/tasks/kernelargs.yml
Labels: approved, lgtm

#729 Allow for manual trigger of the molecule test workflow
  .github/workflows/molecule.yaml
Labels: approved, lgtm

#726 Don't use log files on EDPM nodes for networking related services
  roles/edpm_neutron_dhcp/defaults/main.yml
  roles/edpm_neutron_dhcp/meta/argument_specs.yml
  roles/edpm_neutron_dhcp/molecule/default/tests/test_neutron_dhcp.py
  roles/edpm_neutron_dhcp/tasks/install.yml
  roles/edpm_neutron_dhcp/templates/kolla_config/neutron_dhcp_agent.yaml.j2
  roles/edpm_neutron_dhcp/templates/neutron.conf.j2
  roles/edpm_neutron_dhcp/templates/wrappers/kill-script.j2
  roles/edpm_neutron_metadata/defaults/main.yml
  roles/edpm_neutron_metadata/meta/argument_specs.yml
  roles/edpm_neutron_metadata/tasks/install.yml
  roles/edpm_neutron_metadata/templates/kolla_ovn_metadata_agent.yaml.j2
  roles/edpm_neutron_metadata/templates/wrappers/common_part.j2
  roles/edpm_neutron_metadata/templates/wrappers/kill-script.j2
  roles/edpm_neutron_metadata/templates/wrappers/kill-script_common_part.j2
  roles/edpm_neutron_ovn/defaults/main.yml
  roles/edpm_neutron_ovn/meta/argument_specs.yml
  roles/edpm_neutron_ovn/tasks/install.yml
  roles/edpm_neutron_ovn/templates/kolla_ovn_agent.yaml.j2
  roles/edpm_neutron_sriov/defaults/main.yml
  roles/edpm_neutron_sriov/meta/argument_specs.yml
  roles/edpm_neutron_sriov/molecule/default/verify.yml
  roles/edpm_neutron_sriov/tasks/install.yml
  roles/edpm_neutron_sriov/templates/kolla_config/neutron_sriov_agent.yaml.j2
  roles/edpm_neutron_sriov/templates/neutron.conf.j2
  roles/edpm_ovn/defaults/main.yml
  roles/edpm_ovn/meta/argument_specs.yml
  roles/edpm_ovn/tasks/install.yml
  roles/edpm_ovn/templates/kolla_ovn_controller.yaml.j2
  roles/edpm_ovn_bgp_agent/defaults/main.yml
  roles/edpm_ovn_bgp_agent/molecule/default/verify.yml
  roles/edpm_ovn_bgp_agent/tasks/install.yml
  roles/edpm_ovn_bgp_agent/tasks/install_ovn.yml
  roles/edpm_ovn_bgp_agent/templates/kolla_config/bgp_ovn_controller.yaml.j2
  roles/edpm_ovn_bgp_agent/templates/kolla_config/nb_db_server.yaml.j2
  roles/edpm_ovn_bgp_agent/templates/kolla_config/northd.yaml.j2
  roles/edpm_ovn_bgp_agent/templates/kolla_config/ovn_bgp_agent.yaml.j2
  roles/edpm_ovn_bgp_agent/templates/kolla_config/sb_db_server.yaml.j2
Labels: approved, lgtm, ok-to-test
