Repository openstack-k8s-operators/edpm-ansible, pull requests merged in 2025-06, with the labels that each got.

#964 Create tls config in ceilometer_ipmi for ceilometer_exporter
  roles/edpm_telemetry_power_monitoring/tasks/configure.yml
  roles/edpm_telemetry_power_monitoring/tasks/exporter_tls.yml
  roles/edpm_telemetry_power_monitoring/templates/ceilometer_agent_ipmi.json.j2
  roles/edpm_telemetry_power_monitoring/templates/ceilometer_prom_exporter.yaml.j2
Labels: lgtm

#971 Follow-ups from split update review
  roles/edpm_update_services/tasks/packages.yml
  roles/edpm_update_system/tasks/kpatch.yml
  roles/edpm_update_system/tasks/main.yml
  roles/edpm_update_system/tasks/packages.yml
Labels: approved, lgtm

#979 Ability to customize the list of RPMs included in system and services update
  roles/edpm_update_services/defaults/main.yml
  roles/edpm_update_services/meta/argument_specs.yml
  roles/edpm_update_services/tasks/packages.yml
  roles/edpm_update_system/defaults/main.yml
  roles/edpm_update_system/meta/argument_specs.yml
  roles/edpm_update_system/tasks/packages.yml
Labels: approved, lgtm

#908 Default nmstate provider changes
  roles/edpm_bootstrap/defaults/main.yml
  roles/edpm_bootstrap/meta/argument_specs.yml
  roles/edpm_bootstrap/tasks/bootstrap.yml
  roles/edpm_network_config/defaults/main.yml
  roles/edpm_network_config/meta/argument_specs.yml
  roles/edpm_network_config/molecule/default/prepare.yml
  roles/edpm_network_config/molecule/nmstate/prepare.yml
  roles/edpm_network_config/tasks/dns_nm_configs.yml
  roles/edpm_network_config/tasks/main.yml
Labels: approved, lgtm

#968 Improvements to download retries in roles
  roles/edpm_bootstrap/defaults/main.yml
  roles/edpm_frr/defaults/main.yml
  roles/edpm_iscsid/defaults/main.yml
  roles/edpm_kernel/defaults/main.yml
  roles/edpm_libvirt/defaults/main.yml
  roles/edpm_logrotate_crond/defaults/main.yml
  roles/edpm_multipathd/defaults/main.yml
  roles/edpm_network_config/defaults/main.yml
  roles/edpm_neutron_dhcp/defaults/main.yml
  roles/edpm_neutron_metadata/defaults/main.yml
  roles/edpm_neutron_ovn/defaults/main.yml
  roles/edpm_neutron_sriov/defaults/main.yml
  roles/edpm_nova/defaults/main.yml
  roles/edpm_ovn/defaults/main.yml
  roles/edpm_ovn_bgp_agent/defaults/main.yml
  roles/edpm_ovs/defaults/main.yml
  roles/edpm_podman/defaults/main.yml
  roles/edpm_sshd/defaults/main.yml
  roles/edpm_swift/defaults/main.yml
  roles/edpm_telemetry/defaults/main.yml
  roles/edpm_telemetry_power_monitoring/defaults/main.yml
  roles/edpm_tuned/defaults/main.yml
Labels: approved
